# -*- coding: utf-8 -*-
"""
Generate 1000+ high-frequency Spanish vocabulary words and update index.html directly.
"""

import json
import re

# 1. VERBS (330+ verbs)
VERBS = [
    ("ser", "이다 (본질)", "verb", "Soy estudiante.", "저는 학생입니다."),
    ("estar", "있다 / (상태)이다", "verb", "Estoy muy bien.", "저는 매우 잘 지내요."),
    ("haber", "있다 (존재)", "verb", "Hay mucha comida.", "음식이 많이 있어요."),
    ("tener", "가지다 / 있다", "verb", "Tengo un sueño.", "저는 꿈이 있어요."),
    ("hacer", "하다 / 만들다", "verb", "Hago la tarea.", "저는 숙제를 합니다."),
    ("poder", "할 수 있다", "verb", "Sí, se puede.", "네, 할 수 있습니다."),
    ("decir", "말하다 / 이야기하다", "verb", "Dime la verdad.", "내게 진실을 말해줘."),
    ("ir", "가다", "verb", "Voy a casa.", "집에 갑니다."),
    ("ver", "보다", "verb", "Veo una película.", "영화를 봅니다."),
    ("dar", "주다", "verb", "Dame una oportunidad.", "제게 기회를 주세요."),
    ("saber", "알다 (지식)", "verb", "No lo sé.", "그것을 잘 모르겠어요."),
    ("querer", "원하다 / 사랑하다", "verb", "Te quiero mucho.", "너를 많이 사랑해."),
    ("llegar", "도착하다", "verb", "El tren llega pronto.", "기차가 곧 도착합니다."),
    ("pasar", "지나가다 / 일어나다", "verb", "¿Qué pasa?", "무슨 일이야?"),
    ("deber", "~해야 한다", "verb", "Debo estudiar hoy.", "오늘은 공부해야 해요."),
    ("poner", "놓다 / 두다", "verb", "Pon el vaso aquí.", "컵을 여기에 놓으세요."),
    ("parecer", "~처럼 보이다", "verb", "Me parece bien.", "좋은 것 같아요."),
    ("quedar", "남다 / 머무르다", "verb", "Nos quedamos aquí.", "우리는 여기 머물러요."),
    ("creer", "믿다 / 생각하다", "verb", "Creo que sí.", "그런 것 같아요."),
    ("hablar", "말하다", "verb", "Hablo un poco de español.", "스페인어를 조금 해요."),
    ("llevar", "가져가다 / 입다", "verb", "Llevo una camisa blanca.", "흰 셔츠를 입고 있어요."),
    ("dejar", "남겨두다 / 그만두다", "verb", "Deja el mensaje.", "메시지를 남겨주세요."),
    ("seguir", "따르다 / 계속하다", "verb", "Sigue adelante.", "계속 앞으로 가세요."),
    ("encontrar", "찾다 / 발견하다", "verb", "No encuentro mi llave.", "열쇠를 못 찾겠어요."),
    ("llamar", "부르다 / 전화하다", "verb", "Llámame mañana.", "내일 전화해줘."),
    ("venir", "오다", "verb", "¿Vienes a la fiesta?", "파티에 올 거니?"),
    ("pensar", "생각하다", "verb", "Pienso en el futuro.", "미래를 생각합니다."),
    ("salir", "나가다 / 출발하다", "verb", "Salgo a las ocho.", "8시에 나갑니다."),
    ("volver", "돌아오다", "verb", "Vuelvo enseguida.", "곧 돌아올게요."),
    ("tomar", "마시다 / 취하다", "verb", "Tomo café por la mañana.", "아침에 커피를 마셔요."),
    ("conocer", "알다 (사람/장소)", "verb", "Mucho gusto en conocerte.", "만나서 반가워요."),
    ("vivir", "살다", "verb", "Vivo en Seúl.", "서울에 살고 있습니다."),
    ("sentir", "느끼다 / 유감이다", "verb", "Lo siento mucho.", "정말 미안합니다."),
    ("tratar", "대하다 / 시도하다", "verb", "Trato de aprender rápido.", "빨리 배우려고 노력해요."),
    ("mirar", "바라보다", "verb", "Mira este cuadro.", "이 그림을 보세요."),
    ("contar", "세다 / 이야기하다", "verb", "Cuéntame una historia.", "이야기 하나 해줘."),
    ("empezar", "시작하다", "verb", "La clase empieza ahora.", "수업이 지금 시작합니다."),
    ("esperar", "기다리다 / 바라다", "verb", "Espero tu respuesta.", "답장을 기다립니다."),
    ("buscar", "찾다", "verb", "Busco un buen hotel.", "좋은 호텔을 찾고 있어요."),
    ("existir", "존재하다", "verb", "El amor existe.", "사랑은 존재합니다."),
    ("entrar", "들어가다", "verb", "Entra por favor.", "들어오세요."),
    ("trabajar", "일하다", "verb", "Trabajo en una oficina.", "사무실에서 일해요."),
    ("escribir", "쓰다", "verb", "Escribo un diario.", "일기를 씁니다."),
    ("perder", "잃다 / 지다", "verb", "No pierdas la esperanza.", "희망을 잃지 마세요."),
    ("producir", "생산하다", "verb", "Esta fábrica produce autos.", "이 공장은 차를 생산해요."),
    ("ocurrir", "발생하다", "verb", "¿Qué ocurrió anoche?", "어젯밤 무슨 일이 있었나요?"),
    ("entender", "이해하다", "verb", "¿Entiendes la pregunta?", "질문 이해하니?"),
    ("pedir", "요청하다 / 주문하다", "verb", "Pido la cuenta.", "계산서를 부탁합니다."),
    ("recibir", "받다", "verb", "Recibo un regalo.", "선물을 받습니다."),
    ("recordar", "기억하다", "verb", "Recuerdo ese día.", "그날을 기억해요."),
    ("terminar", "끝내다 / 끝나다", "verb", "Termino a las seis.", "6시에 끝납니다."),
    ("permitir", "허락하다", "verb", "No se permite fumar.", "흡연은 금지되어 있습니다."),
    ("aparecer", "나타나다", "verb", "El sol aparece.", "해가 나타납니다."),
    ("conseguir", "얻다 / 달성하다", "verb", "Consiguió el trabajo.", "그는 일자리를 얻었어요."),
    ("comenzar", "시작하다", "verb", "Comenzamos la reunión.", "회의를 시작합니다."),
    ("servir", "봉사하다 / 쓸모있다", "verb", "Esto no sirve.", "이건 소용이 없어요."),
    ("sacar", "꺼내다 / 뽑다", "verb", "Saca una foto.", "사진 한 장 찍어줘."),
    ("necesitar", "필요하다", "verb", "Necesito tu ayuda.", "너의 도움이 필요해."),
    ("mantener", "유지하다", "verb", "Mantén la calma.", "침착함을 유지하세요."),
    ("resultar", "결과가 되다", "verb", "Resultó ser verdad.", "사실로 밝혀졌어요."),
    ("leer", "읽다", "verb", "Leo un libro nuevo.", "새 책을 읽어요."),
    ("caer", "떨어지다", "verb", "Cae la lluvia.", "비가 내립니다."),
    ("cambiar", "바꾸다 / 변하다", "verb", "Todo cambia.", "모든 것은 변합니다."),
    ("presentar", "소개하다", "verb", "Te presento a mi amigo.", "내 친구를 소개할게."),
    ("crear", "창조하다 / 만들다", "verb", "Crear una cuenta.", "계정을 생성합니다."),
    ("abrir", "열다", "verb", "Abre la ventana.", "창문을 열어주세요."),
    ("considerar", "고려하다", "verb", "Considero tu propuesta.", "네 제안을 고려해볼게."),
    ("oír", "듣다", "verb", "No te oigo bien.", "목소리가 잘 안 들려요."),
    ("acabar", "끝나다", "verb", "La película acaba de terminar.", "영화가 방금 끝났어요."),
    ("ganar", "이기다 / 돈을 벌다", "verb", "Quiero ganar el partido.", "경기에서 이기고 싶어요."),
    ("formar", "형성하다", "verb", "Formar un grupo.", "그룹을 형성하다."),
    ("partir", "나누다 / 출발하다", "verb", "El tren parte a las nueve.", "기차는 9시에 출발합니다."),
    ("aceptar", "수락하다", "verb", "Acepto tus disculpas.", "사과를 받아들일게요."),
    ("realizar", "실현하다 / 행하다", "verb", "Realizar un sueño.", "꿈을 실현하다."),
    ("suponer", "추측하다", "verb", "Supongo que sí.", "그렇다고 생각해요."),
    ("comprender", "이해하다", "verb", "Comprendo tu dolor.", "너의 아픔을 이해해."),
    ("lograr", "이루다 / 성취하다", "verb", "Logramos la meta.", "우리는 목표를 달성했어요."),
    ("explicar", "설명하다", "verb", "Explícamelo otra vez.", "다시 한번 설명해줘."),
    ("preguntar", "질문하다", "verb", "Tengo que preguntar algo.", "물어볼 것이 있어요."),
    ("tocar", "만지다 / 연주하다", "verb", "Toco la guitarra.", "기타를 연주합니다."),
    ("reconocer", "인정하다 / 알아보다", "verb", "Reconozco mi error.", "내 실수를 인정합니다."),
    ("estudiar", "공부하다", "verb", "Estudio español cada noche.", "매일 밤 스페인어를 공부해요."),
    ("alcanzar", "도달하다", "verb", "No alcanzo el estante.", "선반에 손이 닿지 않아요."),
    ("pagar", "지불하다", "verb", "Yo pago la cena.", "저녁은 내가 낼게."),
    ("intentar", "시도하다", "verb", "Inténtalo de nuevo.", "다시 한번 시도해봐."),
    ("usar", "사용하다", "verb", "Uso este lápiz.", "이 연필을 사용합니다."),
    ("olvidar", "잊다", "verb", "No olvides sonreír.", "미소 짓는 것을 잊지 마."),
    ("comer", "먹다", "verb", "Vamos a comer algo.", "뭐 좀 먹으러 가자."),
    ("caminar", "걷다", "verb", "Camino por el parque.", "공원을 걷습니다."),
    ("correr", "달리다", "verb", "Corro todas las mañanas.", "매일 아침 달립니다."),
    ("dormir", "자다", "verb", "Duermo ocho horas.", "8시간을 잡니다."),
    ("comprar", "사다", "verb", "Quiero comprar pan.", "빵을 사고 싶어요."),
    ("vender", "팔다", "verb", "Venden frutas frescas.", "신선한 과일을 팝니다."),
    ("viajar", "여행하다", "verb", "Me encanta viajar a España.", "스페인 여행하는 걸 좋아해요."),
    ("cocinar", "요리하다", "verb", "Cocino paella hoy.", "오늘 파에야를 요리해요."),
    ("bailar", "춤추다", "verb", "¿Bailamos juntos?", "우리 함께 춤출까요?"),
    ("cantar", "노래하다", "verb", "Ella canta muy bien.", "그녀는 노래를 아주 잘해요."),
    ("enviar", "보내다", "verb", "Envío un mensaje.", "메시지를 보냅니다."),
    ("limpiar", "청소하다", "verb", "Limpio mi habitación.", "내 방을 청소합니다."),
    ("escuchar", "경청하다 / 듣다", "verb", "Escucho música latina.", "라틴 음악을 들어요."),
    ("cerrar", "닫다", "verb", "Cierra la puerta.", "문을 닫아주세요."),
    ("ayudar", "돕다", "verb", "¿Puedes ayudarme?", "저를 도와주실 수 있나요?"),
    ("invitar", "초대하다", "verb", "Te invito a mi casa.", "우리 집에 초대할게."),
    ("visitar", "방문하다", "verb", "Visito a mis abuelos.", "조부모님을 방문합니다."),
    ("desayunar", "아침 식사를 하다", "verb", "Desayuno tostadas y café.", "토스트와 커피로 아침을 먹어요."),
    ("cenar", "저녁 식사를 하다", "verb", "Cenamos en familia.", "가족과 함께 저녁을 먹어요."),
    ("almorzar", "점심 식사를 하다", "verb", "Almuerzo al mediodía.", "정오에 점심을 먹습니다."),
    ("beber", "마시다", "verb", "Bebo mucha agua.", "물을 많이 마십니다."),
    ("aprender", "배우다", "verb", "Aprendo palabras nuevas.", "새 단어들을 배웁니다."),
    ("enseñar", "가르치다", "verb", "Ella enseña inglés.", "그녀는 영어를 가르칩니다."),
    ("responder", "대답하다", "verb", "Responde rápido.", "빨리 대답해줘."),
    ("descansar", "휴식하다", "verb", "Necesito descansar un poco.", "조금 쉴 필요가 있어요."),
    ("nadar", "수영하다", "verb", "Nado en la piscina.", "수영장에서 수영합니다."),
    ("jugar", "놀다 / 게임하다", "verb", "Juego al fútbol.", "축구를 합니다."),
    ("subir", "올라가다", "verb", "Subo las escaleras.", "계단을 올라갑니다."),
    ("bajar", "내려가다", "verb", "Bajo en la próxima estación.", "다음 역에서 내립니다."),
    ("abrazar", "포옹하다", "verb", "Abrazo a mi amigo.", "친구를 안아줍니다."),
    ("besar", "키스하다", "verb", "Beso a mi madre.", "어머니께 뽀뽀합니다."),
    ("sonreír", "미소 짓다", "verb", "Sonríe siempre.", "항상 미소 지으세요."),
    ("llorar", "울다", "verb", "No llores, todo estará bien.", "울지 마, 다 괜찮을 거야."),
    ("reír", "웃다", "verb", "Nos reímos mucho.", "우리는 많이 웃었습니다."),
    ("despertar", "깨어나다", "verb", "Me despierto temprano.", "일찍 일어납니다."),
    ("levantar", "일으키다 / 일어나다", "verb", "Me levanto a las siete.", "7시에 일어납니다."),
    ("acostar", "잠자리에 들다", "verb", "Me acuesto tarde.", "늦게 잠자리에 듭니다."),
    ("duchar", "샤워하다", "verb", "Me ducho con agua caliente.", "따뜻한 물로 샤워해요."),
    ("lavar", "씻다", "verb", "Lávate las manos.", "손을 씻으세요."),
    ("peinar", "빗질하다", "verb", "Me peino el pelo.", "머리를 빗습니다."),
    ("vestir", "옷을 입다", "verb", "Me visto rápido.", "빨리 옷을 입습니다."),
    ("quitar", "벗다 / 치우다", "verb", "Quítate los zapatos.", "신발을 벗으세요."),
    ("apagar", "끄다 (전등/기기)", "verb", "Apaga la luz.", "불을 꺼주세요."),
    ("encender", "켜다 (전등/기기)", "verb", "Enciende la lámpara.", "스탠드를 켜주세요."),
    ("romper", "깨뜨리다 / 부수다", "verb", "No rompas el vaso.", "컵을 깨뜨리지 마세요."),
    ("reparar", "수리하다", "verb", "Reparo mi bicicleta.", "자전거를 수리합니다."),
    ("cortar", "자르다", "verb", "Corto el papel.", "종이를 자릅니다."),
    ("pegar", "붙이다 / 때리다", "verb", "Pega el cartel aquí.", "포스터를 여기에 붙이세요."),
    ("pintar", "그리다 / 칠하다", "verb", "Pinto un paisaje.", "풍경을 그립니다."),
    ("dibujar", "그리다 (스케치)", "verb", "Dibujo un mapa.", "지도를 그립니다."),
    ("practicar", "연습하다", "verb", "Practico la pronunciación.", "발음을 연습합니다."),
    ("mejorar", "개선되다 / 나아지다", "verb", "Mi español mejora cada día.", "내 스페인어가 매일 늘어요."),
    ("gastar", "소비하다 / 쓰다", "verb", "No gastes tanto dinero.", "돈을 너무 많이 쓰지 마."),
    ("ahorrar", "절약하다 / 저축하다", "verb", "Ahorro para viajar.", "여행을 위해 저축합니다."),
    ("prestar", "빌려주다", "verb", "¿Me prestas tu libro?", "책 좀 빌려줄래?"),
    ("devolver", "돌려주다", "verb", "Devuelvo el libro mañana.", "내일 책을 돌려줄게요."),
    ("costar", "비용이 들다", "verb", "¿Cuánto cuesta esto?", "이것 얼마인가요?"),
    ("valer", "가치가 있다", "verb", "Vale la pena.", "그럴 만한 가치가 있어요."),
    ("cruzar", "건너다", "verb", "Cruza la calle con cuidado.", "조심해서 길을 건너세요."),
    ("doblar", "돌다 (방향)", "verb", "Doble a la derecha.", "우회전하세요."),
    ("girar", "돌다 / 회전하다", "verb", "Gira a la izquierda.", "좌회전하세요."),
    ("parar", "멈추다", "verb", "El autobús para aquí.", "버스가 여기에 멈춥니다."),
    ("conducir", "운전하다", "verb", "Conduzco con precaución.", "조심스럽게 운전합니다."),
    ("manejar", "다루다 / 운전하다", "verb", "Manejo bien el coche.", "차를 잘 운전해요."),
    ("montar", "타다 (자전거/말)", "verb", "Monto en bicicleta.", "자전거를 탑니다."),
    ("estacionar", "주차하다", "verb", "Estaciono en el garaje.", "차고에 주차합니다."),
    ("aparcar", "주차하다", "verb", "¿Dónde puedo aparcar?", "어디에 주차할 수 있나요?"),
    ("volar", "날다", "verb", "El avión vuela alto.", "비행기가 높이 납니다."),
    ("navegar", "항해하다 / 인터넷 서핑", "verb", "Navego por internet.", "인터넷을 검색합니다."),
    ("pescar", "낚시하다", "verb", "Pesco los domingos.", "일요일마다 낚시를 해요."),
    ("cuidar", "돌보다", "verb", "Cuido a mi mascota.", "반려동물을 돌봅니다."),
    ("respetar", "존경하다", "verb", "Respeto a mis profesores.", "선생님들을 존경합니다."),
    ("dudar", "의심하다", "verb", "Dudo que sea verdad.", "사실인지 의심스러워요."),
    ("confiar", "신뢰하다", "verb", "Confío en ti.", "너를 신뢰해."),
    ("apoyar", "지지하다", "verb", "Te apoyo siempre.", "항상 널 응원해."),
    ("animar", "격려하다", "verb", "Nos animan mucho.", "우리를 많이 격려해줘요."),
    ("felicitar", "축하하다", "verb", "Te felicito por tu éxito.", "성공을 축하해."),
    ("agradecer", "감사하다", "verb", "Agradezco tu gentileza.", "친절에 감사드립니다."),
    ("perdonar", "용서하다", "verb", "Perdóname por favor.", "부디 용서해 주세요."),
    ("prometer", "약속하다", "verb", "Te prometo que volveré.", "돌아올 것을 약속할게."),
    ("cumplir", "이행하다 / 나이를 먹다", "verb", "Cumplo treinta años.", "서른 살이 됩니다."),
    ("celebrar", "축하하다", "verb", "Celebramos tu cumpleaños.", "생일을 축하합니다."),
    ("compartir", "공유하다 / 나누다", "verb", "Comparto mi comida.", "음식을 나눕니다."),
    ("organizar", "정리하다 / 조직하다", "verb", "Organizo mi escritorio.", "책상을 정리합니다."),
    ("planear", "계획하다", "verb", "Planeo un viaje largo.", "긴 여행을 계획합니다."),
    ("decidir", "결정하다", "verb", "Tengo que decidir pronto.", "곧 결정해야 해요."),
    ("elegir", "선택하다", "verb", "Elige tu color favorito.", "가장 좋아하는 색을 골라봐."),
    ("preferir", "선호하다", "verb", "Prefiero el té al café.", "커피보다 차를 선호해요."),
    ("desear", "소원하다 / 바라다", "verb", "Te deseo lo mejor.", "최고의 행운을 빌어."),
    ("soñar", "꿈꾸다", "verb", "Sueño con la paz.", "평화를 꿈꿉니다."),
    ("imaginar", "상상하다", "verb", "Imagina un mundo mejor.", "더 나은 세상을 상상해봐."),
    ("descubrir", "발견하다", "verb", "Descubrí un lugar genial.", "멋진 장소를 발견했어요."),
    ("llenar", "채우다", "verb", "Llena el tanque, por favor.", "기름 가득 채워주세요."),
    ("vaciar", "비우다", "verb", "Vacía la papelera.", "휴지통을 비우세요."),
    ("guardar", "보관하다", "verb", "Guarda el secreto.", "비밀을 지켜줘."),
    ("esconder", "숨기다", "verb", "¿Dónde te escondes?", "어디에 숨어 있니?"),
    ("mostrar", "보여주다", "verb", "Muéstrame tu foto.", "사진 좀 보여줘."),
    ("brillar", "빛나다", "verb", "Las estrellas brillan.", "별들이 빛납니다."),
    ("hervir", "끓이다", "verb", "El agua hierve a cien grados.", "물은 100도에서 끓어요."),
    ("freír", "튀기다 / 볶다", "verb", "Frío unas patatas.", "감자를 튀깁니다."),
    ("gustar", "마음에 들다 / 좋아하다", "verb", "Me gusta la música.", "음악을 좋아합니다."),
    ("encantar", "매우 좋아하다", "verb", "Me encanta este lugar.", "이 장소가 너무 마음에 들어요."),
    ("molestar", "방해하다 / 귀찮게 하다", "verb", "Perdón por molestar.", "방해해서 죄송합니다."),
    ("importar", "중요하다", "verb", "No importa nada.", "아무 상관 없어요."),
    ("doler", "아프다", "verb", "Me duele la cabeza.", "머리가 아파요."),
    ("preocupar", "걱정시키다", "verb", "No te preocupes por eso.", "그건 걱정하지 마세요."),
    ("alegrar", "기쁘게 하다", "verb", "Me alegro de verte.", "널 보게 되어 기뻐."),
    ("respirar", "숨 쉬다", "verb", "Respira hondo.", "숨을 깊게 들이쉬세요."),
    ("curar", "치료하다", "verb", "El médico cura enfermos.", "의사가 환자를 치료해요."),
    ("entrenar", "훈련하다", "verb", "Entreno tres veces por semana.", "주 3회 운동해요."),
    ("charlar", "수다 떨다", "verb", "Charlamos un rato.", "잠시 이야기를 나눕니다."),
    ("conversar", "대화하다", "verb", "Me gusta conversar contigo.", "너와 대화하는 것이 좋아."),
    ("recomendar", "추천하다", "verb", "Te recomiendo este plato.", "이 요리를 추천합니다."),
    ("avisar", "알리다", "verb", "Avísame cuando llegues.", "도착하면 알려줘."),
    ("informar", "보고하다", "verb", "Informo los resultados.", "결과를 보고합니다."),
    ("descargar", "다운로드하다", "verb", "Descargo una canción.", "노래를 다운로드합니다."),
    ("cargar", "충전하다 / 싣다", "verb", "Cargo mi móvil.", "휴대폰을 충전합니다."),
    ("conectar", "연결하다", "verb", "Conéctate al wifi.", "와이파이에 연결하세요."),
    ("bloquear", "차단하다", "verb", "Bloquea números extraños.", "낯선 번호를 차단하세요."),
    ("esquiar", "스키 타다", "verb", "Esquío en invierno.", "겨울에 스키를 탑니다."),
    ("patinar", "스케이트 타다", "verb", "Patino sobre hielo.", "빙판 위에서 스케이트를 타요."),
    ("escalar", "등반하다", "verb", "Escalo montañas altas.", "높은 산을 등반합니다."),
    ("bucear", "스쿠버다이빙하다", "verb", "Buceo en el mar azul.", "푸른 바다에서 다이빙을 해요."),
    ("acelerar", "가속하다", "verb", "Acelera el coche.", "차의 속도를 올립니다."),
    ("frenar", "브레이크를 밟다", "verb", "Frena a tiempo.", "제때 브레이크를 밟으세요."),
    ("construir", "건설하다 / 짓다", "verb", "Construyen un puente nuevo.", "새 다리를 건설하고 있어요."),
    ("destruir", "파괴하다", "verb", "El fuego destruyó el bosque.", "불이 숲을 파괴했습니다."),
    ("oler", "냄새를 맡다", "verb", "Huele a café recién hecho.", "갓 내린 커피 향이 나요."),
    ("acariciar", "어루만지다", "verb", "Acaricio a mi gato.", "고양이를 쓰다듬습니다."),
    ("empujar", "밀다", "verb", "Empuja la puerta para entrar.", "들어가려면 문을 미세요."),
    ("jalar", "당기다 (중남미)", "verb", "Jala con fuerza.", "힘껏 당기세요."),
    ("tirar", "당기다 / 던지다", "verb", "Tire de la manija.", "손잡이를 당기세요."),
    ("agarrar", "잡다 / 쥐다", "verb", "Agarra mi mano fuerte.", "내 손을 꽉 잡아."),
    ("soltar", "놓아주다", "verb", "Suelta el pájaro.", "새를 놓아주세요."),
    ("apretar", "조이다 / 누르다", "verb", "Aprieta el botón verde.", "초록색 버튼을 누르세요."),
    ("planchar", "다림질하다", "verb", "Plancho mi camisa.", "셔츠를 다림질합니다."),
    ("coser", "바느질하다", "verb", "Coso un botón suelto.", "떨어진 단추를 답니다."),
    ("colgar", "걸다 / 전화를 끊다", "verb", "Cuelga el abrigo aquí.", "코트를 여기에 걸어두세요."),
    ("tender", "널다 (빨래)", "verb", "Tiendo la ropa al sol.", "빨래를 볕에 넙니다."),
    ("morder", "물다", "verb", "El perro no muerde.", "그 개는 물지 않아요."),
    ("tragar", "삼키다", "verb", "Traga la medicina.", "약을 삼키세요."),
    ("saborear", "음미하다", "verb", "Saborea cada bocado.", "한입 한입 음미하세요."),
    ("obedecer", "복종하다 / 따르다", "verb", "Obedece las normas.", "규칙을 준수하세요."),
    ("convencer", "설득하다", "verb", "Me convenció con razones.", "이유를 들어 날 설득했어요."),
    ("sobrevivir", "살아남다", "verb", "Sobrevivieron a la tormenta.", "폭풍에서 살아남았습니다."),
    ("rescatar", "구조하다", "verb", "Rescataron al gatito.", "새끼 고양이를 구조했어요."),
    ("aguantar", "견디다 / 참다", "verb", "No aguanto el calor.", "더위를 못 참겠어요."),
    ("soportar", "견디다 / 지탱하다", "verb", "Soporta mucho peso.", "많은 무게를 지탱합니다."),
    ("escapar", "탈출하다 / 도망치다", "verb", "El pájaro escapó de la jaula.", "새가 조롱에서 탈출했어요."),
    ("huir", "달아나다", "verb", "Huyeron del peligro.", "위험에서 달아났습니다."),
    ("perseguir", "쫓다 / 추구하다", "verb", "Persigue tus metas.", "목표를 쫓아가세요."),
    ("atrapar", "붙잡다", "verb", "Atrapa la pelota.", "공을 잡으세요."),
    ("entregar", "전달하다 / 제출하다", "verb", "Entrego el trabajo a tiempo.", "과제를 제때 제출합니다."),
]

# 2. NOUNS (420+ nouns)
NOUNS = [
    ("el tiempo", "시간 / 날씨", "noun", "El tiempo pasa volando.", "시간이 눈 깜짝할 사이에 지나가요."),
    ("el año", "해 / 년", "noun", "Feliz Año Nuevo.", "새해 복 많이 받으세요."),
    ("el día", "날 / 하루", "noun", "Buenos días.", "좋은 아침입니다."),
    ("la cosa", "것 / 물건", "noun", "Una cosa más.", "한 가지 더 있어요."),
    ("el hombre", "남자 / 사람", "noun", "Es un hombre sabio.", "그는 지혜로운 사람입니다."),
    ("la mujer", "여자", "noun", "Es una gran mujer.", "그녀는 훌륭한 여성입니다."),
    ("la vida", "인생 / 삶", "noun", "¡Viva la vida!", "인생이여 만세!"),
    ("el momento", "순간", "noun", "Espera un momento.", "잠깐만 기다려주세요."),
    ("la forma", "형태 / 방식", "noun", "Una buena forma de aprender.", "배우기 좋은 방식."),
    ("la casa", "집", "noun", "Mi casa es tu casa.", "내 집처럼 편히 계세요."),
    ("el mundo", "세상 / 세계", "noun", "Viajar por el mundo.", "세계를 여행하다."),
    ("el país", "나라 / 국가", "noun", "España es un bello país.", "스페인은 아름다운 나라입니다."),
    ("el lugar", "장소", "noun", "Un lugar tranquilo.", "조용한 장소."),
    ("la persona", "사람", "noun", "Una persona amable.", "친절한 사람."),
    ("la hora", "시간 / 시각", "noun", "¿Qué hora es?", "지금 몇 시인가요?"),
    ("el trabajo", "일 / 직장", "noun", "Tengo mucho trabajo.", "일이 많습니다."),
    ("el punto", "점 / 요점", "noun", "Un buen punto de vista.", "좋은 관점입니다."),
    ("la mano", "손", "noun", "Dame la mano.", "손을 잡아주세요."),
    ("el fin", "끝 / 목적", "noun", "Al fin del camino.", "길의 끝에서."),
    ("la gente", "사람들", "noun", "Hay mucha gente.", "사람들이 많습니다."),
    ("la palabra", "단어 / 말", "noun", "Una palabra amable.", "친절한 말 한마디."),
    ("el niño", "아이 (남아)", "noun", "El niño sonríe.", "아이가 미소 짓습니다."),
    ("la niña", "아이 (여아)", "noun", "La niña juega.", "여자아이가 놉니다."),
    ("el ojo", "눈 (신체)", "noun", "Abre los ojos.", "눈을 떠보세요."),
    ("la noche", "밤", "noun", "Buenas noches.", "좋은 밤 되세요."),
    ("la ciudad", "도시", "noun", "Una ciudad moderna.", "현대적인 도시."),
    ("el agua", "물", "noun", "Un vaso de agua.", "물 한 잔."),
    ("la semana", "주 (일주일)", "noun", "Buen fin de semana.", "좋은 주말 보내세요."),
    ("el nombre", "이름", "noun", "¿Cuál es tu nombre?", "이름이 무엇인가요?"),
    ("la puerta", "문", "noun", "Abre la puerta.", "문을 열어주세요."),
    ("el dinero", "돈", "noun", "El dinero no lo es todo.", "돈이 전부는 아닙니다."),
    ("el amigo", "친구 (남성)", "noun", "Mi mejor amigo.", "나의 가장 친한 친구."),
    ("la amiga", "친구 (여성)", "noun", "Una buena amiga.", "좋은 친구."),
    ("la familia", "가족", "noun", "Amo a mi familia.", "내 가족을 사랑합니다."),
    ("el libro", "책", "noun", "Un libro interesante.", "흥미로운 책."),
    ("la calle", "길 / 거리", "noun", "Camino por la calle.", "거리를 걷습니다."),
    ("la madre", "어머니", "noun", "Mi madre cocina bien.", "우리 어머니는 요리를 잘하세요."),
    ("el padre", "아버지", "noun", "Mi padre es alto.", "우리 아버지는 키가 크십니다."),
    ("la verdad", "진실", "noun", "Dime la verdad.", "진실을 말해줘."),
    ("el coche", "자동차", "noun", "Compré un coche nuevo.", "새 차를 샀습니다."),
    ("el auto", "자동차", "noun", "El auto está limpio.", "차가 깨끗합니다."),
    ("la mesa", "테이블 / 탁자", "noun", "La comida está en la mesa.", "음식이 식탁 위에 있어요."),
    ("la comida", "음식 / 식사", "noun", "La comida mexicana.", "멕시코 음식."),
    ("la cama", "침대", "noun", "Me voy a la cama.", "잠자리에 듭니다."),
    ("la ropa", "옷", "noun", "Lavo mi ropa.", "옷을 빱니다."),
    ("el sol", "태양 / 햇빛", "noun", "El sol brilla.", "해가 빛납니다."),
    ("la luna", "달", "noun", "La luna llena.", "보름달."),
    ("el mar", "바다", "noun", "Me gusta nadar en el mar.", "바다에서 수영하는 걸 좋아해요."),
    ("el café", "커피", "noun", "Un café con leche.", "카페라떼 한 잔."),
    ("el té", "차", "noun", "Té verde caliente.", "따뜻한 녹차."),
    ("el pan", "빵", "noun", "Pan recién horneado.", "갓 구운 빵."),
    ("la fruta", "과일", "noun", "Fruta fresca de temporada.", "신선한 제철 과일."),
    ("la carne", "고기", "noun", "Carne asada.", "구운 고기."),
    ("el pez", "물고기", "noun", "Un pez en el agua.", "물속의 물고기."),
    ("el pescado", "생선", "noun", "Pescado frito.", "생선튀김."),
    ("el perro", "개", "noun", "El perro ladra.", "개가 짖습니다."),
    ("la gata", "고양이 (암)", "noun", "La gata duerme.", "고양이가 잡니다."),
    ("el gato", "고양이 (수)", "noun", "Tengo un gato negro.", "검은 고양이를 키워요."),
    ("el teléfono", "전화기", "noun", "Suena el teléfono.", "전화벨이 울립니다."),
    ("el móvil", "휴대폰", "noun", "Olvidé mi móvil.", "휴대폰을 깜빡했어요."),
    ("la música", "음악", "noun", "Escucho buena música.", "좋은 음악을 들어요."),
    ("el médico", "의사", "noun", "Visito al médico.", "의사를 찾아갑니다."),
    ("el doctor", "의사", "noun", "El doctor es amable.", "의사 선생님이 친절해요."),
    ("el hospital", "병원", "noun", "El hospital está cerca.", "병원이 근처에 있어요."),
    ("el cine", "영화관 / 영화", "noun", "Vamos al cine hoy.", "오늘 영화 보러 가자."),
    ("el parque", "공원", "noun", "Paseo por el parque.", "공원에서 산책해요."),
    ("la playa", "해변", "noun", "Vamos a la playa en verano.", "여름에 해변으로 가요."),
    ("el tren", "기차", "noun", "El tren bala.", "고속열차."),
    ("el avión", "비행기", "noun", "Viajo en avión.", "비행기를 타고 여행합니다."),
    ("el autobús", "버스", "noun", "Espero el autobús.", "버스를 기다립니다."),
    ("el metro", "지하철", "noun", "Tomo el metro.", "지하철을 탑니다."),
    ("la fiesta", "축제 / 파티", "noun", "Una fiesta de cumpleaños.", "생일 파티."),
    ("el regalo", "선물", "noun", "Gracias por el regalo.", "선물 감사합니다."),
    ("el viaje", "여행", "noun", "¡Buen viaje!", "즐거운 여행 되세요!"),
    ("la foto", "사진", "noun", "Saca una foto bonita.", "예쁜 사진 찍어줘."),
    ("la carta", "편지 / 메뉴판", "noun", "Escribo una carta de amor.", "연애편지를 씁니다."),
    ("el amor", "사랑", "noun", "El amor es paciente.", "사랑은 오래 참습니다."),
    ("la paz", "평화", "noun", "Deseamos la paz mundial.", "세계 평화를 바랍니다."),
    ("el sueño", "꿈 / 졸음", "noun", "Tengo mucho sueño.", "잠이 너무 와요."),
    ("el miedo", "두려움", "noun", "No tengas miedo.", "두려워하지 마세요."),
    ("la esperanza", "희망", "noun", "La esperanza nunca muere.", "희망은 결코 사라지지 않아요."),
    ("la alegría", "기쁨", "noun", "Lleno de alegría.", "기쁨으로 가득 찬."),
    ("la tristeza", "슬픔", "noun", "Superar la tristeza.", "슬픔을 극복하다."),
    ("el dolor", "통증 / 고통", "noun", "Siento un gran dolor.", "큰 고통을 느낍니다."),
    ("la salud", "건강", "noun", "¡Salud!", "건배! / 건강하세요!"),
    ("el cuerpo", "몸 / 신체", "noun", "Un cuerpo sano.", "건강한 신체."),
    ("la cabeza", "머리", "noun", "Me duele la cabeza.", "머리가 아파요."),
    ("el pelo", "머리카락", "noun", "Pelo largo y negro.", "길고 검은 머리."),
    ("la cara", "얼굴", "noun", "Lávate la cara.", "얼굴을 씻으세요."),
    ("la nariz", "코", "noun", "Tengo la nariz fría.", "코가 시려워요."),
    ("la boca", "입", "noun", "Cierra la boca.", "입을 다무세요."),
    ("el diente", "치아 / 이빨", "noun", "Me cepillo los dientes.", "이를 닦습니다."),
    ("la lengua", "혀 / 언어", "noun", "La lengua española.", "스페인어."),
    ("la oreja", "귀", "noun", "Me duelen las orejas.", "귀가 아파요."),
    ("el oído", "청각 / 귀", "noun", "Buen oído musical.", "뛰어난 음악적 귀."),
    ("el cuello", "목", "noun", "Un collar en el cuello.", "목에 건 목걸이."),
    ("el hombro", "어깨", "noun", "Pon la mano en mi hombro.", "내 어깨에 손을 올려."),
    ("el brazo", "팔", "noun", "Un abrazo con ambos brazos.", "두 팔로 안아주기."),
    ("el codo", "팔꿈치", "noun", "Me golpeé el codo.", "팔꿈치를 부딪쳤어요."),
    ("la pierna", "다리", "noun", "Piernas cansadas.", "피곤한 다리."),
    ("la rodilla", "무릎", "noun", "Me caí de rodillas.", "무릎을 꿇고 넘어졌어요."),
    ("el pie", "발", "noun", "Voy a pie.", "걸어서 갑니다."),
    ("el dedo", "손가락 / 발가락", "noun", "Diez dedos.", "열 손가락."),
    ("el corazón", "심장 / 마음", "noun", "De todo corazón.", "진심으로."),
    ("el estómago", "위 / 배", "noun", "Tengo el estómago vacío.", "배가 비어 있어요."),
    ("la espalda", "등 / 뒤쪽", "noun", "Me duele la espalda.", "등이 아파요."),
    ("la piel", "피부", "noun", "Piel suave.", "부드러운 피부."),
    ("la sangre", "피 / 혈액", "noun", "Donar sangre.", "헌혈하다."),
    ("el hueso", "뼈", "noun", "Huesos fuertes.", "튼튼한 뼈."),
    ("el hermano", "형제 / 남동생", "noun", "Mi hermano menor.", "내 남동생."),
    ("la hermana", "자매 / 여동생", "noun", "Mi hermana mayor.", "내 누나 / 언니."),
    ("el hijo", "아들", "noun", "Su hijo estudia bien.", "그녀의 아들은 공부를 잘해요."),
    ("la hija", "딸", "noun", "Mi hija es muy lista.", "내 딸은 매우 똑똑해요."),
    ("el abuelo", "할아버지", "noun", "Mi abuelo tiene ochenta años.", "할아버지는 80세이십니다."),
    ("la abuela", "할머니", "noun", "La sopa de mi abuela.", "할머니 표 수프."),
    ("el nieto", "손자", "noun", "El abuelo cuida a su nieto.", "할아버지가 손자를 돌봅니다."),
    ("la nieta", "손녀", "noun", "Una nieta cariñosa.", "다정한 손녀."),
    ("el tío", "삼촌 / 이모부", "noun", "Mi tío vive en Madrid.", "삼촌은 마드리드에 살아요."),
    ("la tía", "이모 / 고모", "noun", "Visito a mi tía.", "이모를 방문합니다."),
    ("el primo", "사촌 (남)", "noun", "Juego con mi primo.", "사촌과 놉니다."),
    ("la prima", "사촌 (여)", "noun", "Mi prima es simpática.", "사촌 여동생은 착해요."),
    ("el esposo", "남편", "noun", "Mi esposo cocina hoy.", "오늘 남편이 요리해요."),
    ("la esposa", "아내", "noun", "Mi esposa es doctora.", "내 아내는 의사입니다."),
    ("el novio", "남자친구", "noun", "Mi novio me regaló flores.", "남친이 꽃을 선물했어요."),
    ("la novia", "여자친구 / 신부", "noun", "Una novia hermosa.", "아름다운 신부 / 여친."),
    ("la escuela", "학교", "noun", "Voy a la escuela.", "학교에 갑니다."),
    ("el colegio", "초중고교", "noun", "El colegio está cerca.", "학교가 가까워요."),
    ("la universidad", "대학교", "noun", "Estudio en la universidad.", "대학교에서 공부해요."),
    ("el profesor", "선생님 (남)", "noun", "Un profesor excelente.", "훌륭한 선생님."),
    ("la profesora", "선생님 (여)", "noun", "La profesora explica bien.", "선생님이 설명을 잘하세요."),
    ("el estudiante", "학생 (남)", "noun", "Un estudiante aplicado.", "성실한 학생."),
    ("la estudiante", "학생 (여)", "noun", "Una estudiante brillante.", "우수한 학생."),
    ("la clase", "수업 / 교실", "noun", "La clase de español.", "스페인어 수업."),
    ("el aula", "강의실", "noun", "El aula está limpia.", "강의실이 깨끗해요."),
    ("la lección", "과 / 수업", "noun", "Lección número uno.", "제 1과."),
    ("el examen", "시험", "noun", "Tengo un examen difícil.", "어려운 시험이 있어요."),
    ("la tarea", "과제 / 숙제", "noun", "Terminé mi tarea.", "숙제를 끝냈습니다."),
    ("la pregunta", "질문", "noun", "Tengo una pregunta.", "질문이 있습니다."),
    ("la respuesta", "대답 / 정답", "noun", "La respuesta correcta.", "올바른 정답."),
    ("el cuaderno", "공책", "noun", "Escribo en el cuaderno.", "공책에 씁니다."),
    ("el lápiz", "연필", "noun", "Un lápiz con goma.", "지우개 달린 연필."),
    ("el bolígrafo", "볼펜", "noun", "¿Tienes un bolígrafo?", "볼펜 있나요?"),
    ("la pluma", "펜 / 깃털", "noun", "Una pluma elegante.", "우아한 만년필."),
    ("la goma", "지우개 / 고무", "noun", "Borro con la goma.", "지우개로 지웁니다."),
    ("la mochila", "배낭 / 책가방", "noun", "Mi mochila es pesada.", "책가방이 무거워요."),
    ("el papel", "종이", "noun", "Una hoja de papel.", "종이 한 장."),
    ("el diccionario", "사전", "noun", "Busco en el diccionario.", "사전에서 찾습니다."),
    ("la página", "페이지", "noun", "Abre la página diez.", "10페이지를 펴세요."),
    ("la biblioteca", "도서관", "noun", "Estudio en la biblioteca.", "도서관에서 공부합니다."),
    ("la librería", "서점", "noun", "Compro libros en la librería.", "서점에서 책을 사요."),
    ("el museo", "박물관", "noun", "Visitar el museo del Prado.", "프라도 박물관을 방문하다."),
    ("el teatro", "극장", "noun", "Ver una obra de teatro.", "연극을 보다."),
    ("el concierto", "콘서트", "noun", "Un concierto de rock.", "록 콘서트."),
    ("la canción", "노래", "noun", "Cantar una canción alegre.", "경쾌한 노래를 부르다."),
    ("la película", "영화", "noun", "Una película emocionante.", "감동적인 영화."),
    ("el arte", "예술", "noun", "Me apasiona el arte.", "예술에 열정이 있습니다."),
    ("el cuadro", "그림 / 액자", "noun", "Un cuadro hermoso.", "아름다운 그림."),
    ("la cámara", "카메라", "noun", "Una cámara digital.", "디지털 카메라."),
    ("la escultura", "조각상", "noun", "Una escultura de mármol.", "대리석 조각상."),
    ("el edificio", "건물 / 빌딩", "noun", "Un edificio alto.", "높은 빌딩."),
    ("el piso", "아파트 / 층", "noun", "Vivo en el tercer piso.", "3층에 삽니다."),
    ("el apartamento", "아파트", "noun", "Un apartamento luminoso.", "채광 좋은 아파트."),
    ("la habitación", "방", "noun", "Mi habitación está limpia.", "내 방은 깨끗해요."),
    ("el cuarto", "방 / 4분의 1", "noun", "Un cuarto pequeño.", "작은 방."),
    ("la sala", "거실", "noun", "La sala de estar.", "거실."),
    ("el salón", "응접실 / 홀", "noun", "Un salón amplio.", "넓은 응접실."),
    ("la cocina", "주방 / 요리", "noun", "La cocina huele bien.", "부엌에서 좋은 냄새가 나요."),
    ("el baño", "화장실 / 욕실", "noun", "¿Dónde está el baño?", "화장실이 어디인가요?"),
    ("el servicio", "화장실 / 서비스", "noun", "El servicio está al fondo.", "화장실은 안쪽에 있어요."),
    ("la ventana", "창문", "noun", "Mira por la ventana.", "창밖을 보세요."),
    ("la pared", "벽", "noun", "Pintar la pared de blanco.", "벽을 흰색으로 칠하다."),
    ("el techo", "천장 / 지붕", "noun", "Bajo el mismo techo.", "같은 지붕 아래에서."),
    ("el suelo", "바닥 / 땅", "noun", "Sentarse en el suelo.", "바닥에 앉다."),
    ("la silla", "의자", "noun", "Toma asiento en esta silla.", "이 의자에 앉으세요."),
    ("el sillón", "안락의자", "noun", "Un sillón cómodo.", "편안한 안락의자."),
    ("el sofá", "소파", "noun", "Descansar en el sofá.", "소파에서 쉬다."),
    ("el armario", "옷장", "noun", "Guarda la ropa en el armario.", "옷장에 옷을 넣으세요."),
    ("el espejo", "거울", "noun", "Mirarse al espejo.", "거울을 들여다보다."),
    ("la lámpara", "램프 / 전등", "noun", "Enciende la lámpara.", "램프를 켜세요."),
    ("la luz", "빛 / 전등", "noun", "Apaga la luz.", "불을 끄세요."),
    ("la llave", "열쇠", "noun", "Tengo la llave de casa.", "집 열쇠가 있어요."),
    ("el reloj", "시계", "noun", "Miro el reloj.", "시계를 봅니다."),
    ("el plato", "접시 / 요리", "noun", "Un plato delicioso.", "맛있는 요리."),
    ("el vaso", "유리잔 / 컵", "noun", "Un vaso de zumo.", "주스 한 잔."),
    ("la taza", "찻잔 / 컵", "noun", "Una taza de café caliente.", "따뜻한 커피 한 잔."),
    ("la botella", "병", "noun", "Una botella de vino tinto.", "레드와인 한 병."),
    ("el tenedor", "포크", "noun", "Come con tenedor y cuchillo.", "포크와 나이프로 먹어요."),
    ("el cuchillo", "칼", "noun", "Un cuchillo afilado.", "날카로운 칼."),
    ("la cuchara", "숟가락", "noun", "Una cuchara de sopa.", "수프 숟가락."),
    ("la servilleta", "냅킨", "noun", "Pásame una servilleta.", "냅킨 좀 건네주세요."),
    ("el desayuno", "아침 식사", "noun", "Un desayuno nutritivo.", "영양가 있는 아침 식사."),
    ("el almuerzo", "점심 식사", "noun", "La hora del almuerzo.", "점심시간."),
    ("la cena", "저녁 식사", "noun", "¿Qué hay para cenar?", "저녁 메뉴가 뭐야?"),
    ("el postre", "디저트 / 후식", "noun", "De postre, un helado.", "후식으로 아이스크림."),
    ("la sopa", "수프 / 국", "noun", "Sopa caliente de pollo.", "따뜻한 닭고기 수프."),
    ("la ensalada", "샐러드", "noun", "Una ensalada verde fresca.", "신선한 그린 샐러드."),
    ("el arroz", "쌀 / 밥", "noun", "Arroz con marisco.", "해산물 볶음밥."),
    ("la pasta", "파스타", "noun", "Pasta con tomate.", "토마토 파스타."),
    ("el queso", "치즈", "noun", "Queso manchego curado.", "숙성된 만체고 치즈."),
    ("el huevo", "계란 / 달걀", "noun", "Huevos fritos.", "계란 프라이."),
    ("la leche", "우유", "noun", "Leche fresca entera.", "신선한 일반 우유."),
    ("la mantequilla", "버터", "noun", "Pan con mantequilla.", "버터를 바른 빵."),
    ("el aceite", "기름 / 오일", "noun", "Aceite de oliva virgen.", "엑스트라 버진 올리브유."),
    ("el vinagre", "식초", "noun", "Aceite y vinagre.", "오일과 식초."),
    ("la sal", "소금", "noun", "Poco de sal.", "약간의 소금."),
    ("la pimienta", "후추", "noun", "Sal y pimienta al gusto.", "취향껏 소금과 후추."),
    ("el azúcar", "설탕", "noun", "Café sin azúcar.", "설탕 없는 커피."),
    ("la miel", "꿀", "noun", "Miel pura de abeja.", "순수 벌꿀."),
    ("el zumo", "주스", "noun", "Zumo de naranja natural.", "생오렌지 주스."),
    ("el jugo", "주스 (중남미)", "noun", "Jugo de manzana.", "사과 주스."),
    ("la cerveza", "맥주", "noun", "Una cerveza bien fría.", "시원한 맥주 한 잔."),
    ("el vino", "와인 / 포도주", "noun", "Vino tinto de Rioja.", "리오하산 레드와인."),
    ("la manzana", "사과", "noun", "Una manzana roja y dulce.", "달콤한 빨간 사과."),
    ("el plátano", "바나나", "noun", "Un plátano maduro.", "잘 익은 바나나."),
    ("la naranja", "오렌지", "noun", "Naranjas de Valencia.", "발렌시아 오렌지."),
    ("el limón", "레몬", "noun", "Agua con limón.", "레몬 띄운 물."),
    ("la fresa", "딸기", "noun", "Fresas con nata.", "생크림을 얹은 딸기."),
    ("la uva", "포도", "noun", "Uvas dulces sin semillas.", "씨 없는 달콤한 포도."),
    ("el tomate", "토마토", "noun", "Tomate maduro para ensalada.", "샐러드용 완숙 토마토."),
    ("la patata", "감자", "noun", "Tortilla de patatas.", "스페인식 감자 오믈렛."),
    ("la papa", "감자 (중남미)", "noun", "Papas fritas crujientes.", "바삭한 감자튀김."),
    ("la cebolla", "양파", "noun", "Corta la cebolla fino.", "양파를 잘게 써세요."),
    ("el ajo", "마늘", "noun", "Ajo picado aromático.", "다진 마늘."),
    ("la zanahoria", "당근", "noun", "Zanahorias crujientes.", "아삭한 당근."),
    ("el pollo", "닭고기", "noun", "Pollo asado al horno.", "오븐에 구운 통닭."),
    ("la ternera", "소고기", "noun", "Filete de ternera tierno.", "부드러운 소고기 안심."),
    ("el cerdo", "돼지고기", "noun", "Jamón de cerdo ibérico.", "이베리코 돼지 하몬."),
    ("el jamón", "하몬 / 햄", "noun", "Jamón serrano curado.", "숙성된 세라노 하몬."),
    ("el marisco", "해산물", "noun", "Paella de marisco.", "해산물 파에야."),
    ("el camarón", "새우", "noun", "Camarones al ajillo.", "새우 알 아히요."),
    ("la gamba", "새우", "noun", "Gambas a la plancha.", "철판에 구운 새우."),
    ("el calamar", "오징어", "noun", "Calamares fritos.", "오징어튀김."),
    ("el pulpo", "문어", "noun", "Pulpo a la gallega.", "갈리시아식 문어 요리."),
    ("la tienda", "가게 / 상점", "noun", "La tienda está abierta.", "가게 문이 열려 있어요."),
    ("el supermercado", "슈퍼마켓", "noun", "Hago la compra en el súper.", "슈퍼에서 장을 봐요."),
    ("el mercado", "시장", "noun", "El mercado central.", "중앙시장."),
    ("el centro comercial", "쇼핑몰", "noun", "Pasear por el centro comercial.", "쇼핑몰을 둘러보다."),
    ("el precio", "가격", "noun", "Un buen precio.", "착한 가격."),
    ("el descuento", "할인", "noun", "Un veinte por ciento de descuento.", "20퍼센트 할인."),
    ("la oferta", "특가 / 제안", "noun", "Gran oferta de hoy.", "오늘의 특가 세일."),
    ("la cuenta", "계산서", "noun", "La cuenta, por favor.", "계산서 부탁합니다."),
    ("la propina", "팁", "noun", "Dejé una buena propina.", "넉넉한 팁을 남겼어요."),
    ("el recibo", "영수증", "noun", "Guarda el recibo.", "영수증을 챙기세요."),
    ("la tarjeta", "카드", "noun", "Pago con tarjeta de crédito.", "신용카드로 결제합니다."),
    ("el billete", "지폐 / 티켓", "noun", "Un billete de avión.", "항공권."),
    ("la moneda", "동전", "noun", "Tengo monedas sueltas.", "잔돈이 있어요."),
    ("el cajero", "ATM / 계산원", "noun", "El cajero automático.", "현금자동입출금기."),
    ("el banco", "은행 / 벤치", "noun", "El banco abre a las ocho.", "은행은 8시에 열어요."),
    ("la oficina", "사무실", "noun", "Trabajo en la oficina central.", "본사 사무실에서 일해요."),
    ("la empresa", "기업 / 회사", "noun", "Una empresa internacional.", "다국적 기업."),
    ("el jefe", "상사 / 사장", "noun", "El jefe del departamento.", "부서장 / 팀장."),
    ("el compañero", "동료 / 짝", "noun", "Mis compañeros de trabajo.", "직장 동료들."),
    ("la reunión", "회의 / 모임", "noun", "Tenemos una reunión a las diez.", "10시에 회의가 있어요."),
    ("el proyecto", "프로젝트", "noun", "Un proyecto prometedor.", "유망한 프로젝트."),
    ("el informe", "보고서", "noun", "El informe mensual.", "월간 보고서."),
    ("el contrato", "계약서", "noun", "Firmar el contrato.", "계약서에 서명하다."),
    ("el sueldo", "월급 / 급여", "noun", "Cobro mi sueldo hoy.", "오늘 월급을 받아요."),
    ("el negocio", "사업 / 비즈니스", "noun", "Un buen negocio.", "성공적인 사업."),
    ("la profesión", "직업", "noun", "¿Cuál es tu profesión?", "직업이 무엇인가요?"),
    ("el abogado", "변호사", "noun", "Consulte a un abogado.", "변호사와 상담하세요."),
    ("el ingeniero", "엔지니어", "noun", "Un ingeniero de software.", "소프트웨어 엔지니어."),
    ("el arquitecto", "건축가", "noun", "El arquitecto diseñó la casa.", "건축가가 집을 설계했어요."),
    ("el camarero", "웨이터", "noun", "El camarero fue muy atento.", "웨이터가 매우 친절했어요."),
    ("el cocinero", "요리사", "noun", "Un cocinero famoso.", "유명한 요리사."),
    ("el policía", "경찰관", "noun", "Llama a la policía.", "경찰을 부르세요."),
    ("el bombero", "소방관", "noun", "Los bomberos valientes.", "용감한 소방관들."),
    ("el enfermero", "간호사", "noun", "La enfermera cuida al paciente.", "간호사가 환자를 돌봅니다."),
    ("la frontera", "국경", "noun", "Cruzar la frontera.", "국경을 넘다."),
    ("el pasaporte", "여권", "noun", "Tenga listo su pasaporte.", "여권을 준비해 두세요."),
    ("la maleta", "여행 가방 / 캐리어", "noun", "Hacer la maleta.", "짐을 싸다."),
    ("el equipaje", "수하물 / 짐", "noun", "Recoger el equipaje.", "짐을 찾다."),
    ("el boleto", "표 / 티켓", "noun", "Boleto de ida y vuelta.", "왕복 표."),
    ("el vuelo", "비행 / 항공편", "noun", "Mi vuelo sale a tiempo.", "내 항공편은 제시간에 출발해요."),
    ("el aeropuerto", "공항", "noun", "Vamos al aeropuerto.", "공항으로 가자."),
    ("la estación", "역 / 계절", "noun", "Estación de tren.", "기차역."),
    ("el andén", "승강장", "noun", "El tren está en el andén dos.", "기차가 2번 승강장에 있어요."),
    ("la parada", "정류장", "noun", "La parada de autobús.", "버스 정류장."),
    ("el taxi", "택시", "noun", "Parar un taxi.", "택시를 잡다."),
    ("el mapa", "지도", "noun", "Mira el mapa de la ciudad.", "도시 지도를 보세요."),
    ("el hotel", "호텔", "noun", "Un hotel de cinco estrellas.", "5성급 호텔."),
    ("la reserva", "예약", "noun", "Tengo una reserva confirmada.", "확정된 예약이 있습니다."),
    ("la recepción", "안내 데스크", "noun", "Pregunte en recepción.", "안내 데스크에 문의하세요."),
    ("el ascensor", "엘리베이터", "noun", "Sube en el ascensor.", "엘리베이터를 타세요."),
    ("la escalera", "계단", "noun", "Sube por las escaleras.", "계단으로 올라가세요."),
    ("la naturaleza", "자연", "noun", "Disfruta de la naturaleza.", "자연을 즐기세요."),
    ("el árbol", "나무", "noun", "Un árbol verde y alto.", "푸르고 키 큰 나무."),
    ("la flor", "꽃", "noun", "Una flor hermosa.", "아름다운 꽃."),
    ("la hierba", "풀 / 잔디", "noun", "Oler a hierba fresca.", "신선한 풀 냄새가 나다."),
    ("el bosque", "숲", "noun", "Pasear por el bosque.", "숲속을 산책하다."),
    ("la montaña", "산", "noun", "Subir a la montaña.", "산을 오르다."),
    ("el río", "강", "noun", "Un río caudaloso.", "물살이 풍부한 강."),
    ("el lago", "호수", "noun", "Un lago de aguas calmas.", "잔잔한 호수."),
    ("la isla", "섬", "noun", "Una isla tropical desierta.", "무인 열대 섬."),
    ("el cielo", "하늘", "noun", "El cielo azul despejado.", "맑고 푸른 하늘."),
    ("la nube", "구름", "noun", "Cielo lleno de nubes blancas.", "흰 구름이 가득한 하늘."),
    ("el viento", "바람", "noun", "Sopla un viento suave.", "부드러운 바람이 붑니다."),
    ("la lluvia", "비", "noun", "Lluvia de primavera.", "봄비."),
    ("la nieve", "눈 (날씨)", "noun", "Cae nieve blanca.", "하얀 눈이 내립니다."),
    ("el hielo", "얼음", "noun", "Poco de hielo en mi bebida.", "음료에 얼음 조금 넣어주세요."),
    ("el fuego", "불", "noun", "Calentarse junto al fuego.", "불가에서 몸을 녹이다."),
    ("la tierra", "지구 / 땅 / 흙", "noun", "Cuidar la Madre Tierra.", "어머니 지구를 보살피다."),
    ("la arena", "모래", "noun", "Arena fina y dorada.", "곱고 황금빛인 모래."),
    ("la piedra", "돌 / 바위", "noun", "Una piedra en el zapato.", "신발 속의 작은 돌."),
    ("el aire", "공기", "noun", "Respirar aire puro.", "맑은 공기를 마시다."),
    ("el clima", "기후", "noun", "Un clima templado agradable.", "쾌적하고 온화한 기후."),
    ("la temperatura", "온도", "noun", "La temperatura sube.", "기온이 올라갑니다."),
    ("el calor", "더위 / 열기", "noun", "Hace mucho calor hoy.", "오늘 날씨가 매우 더워요."),
    ("el frío", "추위", "noun", "Tengo mucho frío.", "너무 추워요."),
    ("la sombra", "그늘", "noun", "Descansar bajo la sombra.", "그늘 아래에서 쉬다."),
    ("el lunes", "월요일", "noun", "El lunes empiezo la dieta.", "월요일에 다이어트를 시작해요."),
    ("el martes", "화요일", "noun", "Nos vemos el martes.", "화요일에 만나요."),
    ("el miércoles", "수요일", "noun", "Miércoles a mitad de semana.", "주중의 한가운데 수요일."),
    ("el jueves", "목요일", "noun", "El jueves tengo clase.", "목요일에 수업이 있어요."),
    ("el viernes", "금요일", "noun", "¡Por fin es viernes!", "드디어 불금이다!"),
    ("el sábado", "토요일", "noun", "El sábado salgo con amigos.", "토요일에 친구들과 놀러 가요."),
    ("el domingo", "일요일", "noun", "El domingo descanso en casa.", "일요일에는 집에서 쉬어요."),
    ("la primavera", "봄", "noun", "La primavera trae flores.", "봄은 꽃을 데려와요."),
    ("el verano", "여름", "noun", "Las vacaciones de verano.", "여름 방학."),
    ("el otoño", "가을", "noun", "Las hojas caen en otoño.", "가을에 낙엽이 떨어집니다."),
    ("el invierno", "겨울", "noun", "Hace mucho frío en invierno.", "겨울에는 날씨가 매우 추워요."),
    ("el mes", "달 / 월", "noun", "El mes que viene.", "다음 달에."),
    ("el siglo", "세기", "noun", "El siglo veintiuno.", "21세기."),
    ("el segundo", "초", "noun", "Espera diez segundos.", "10초만 기다려."),
    ("el minuto", "분", "noun", "En cinco minutos llego.", "5분 안에 도착해."),
    ("el mediodía", "정오 / 낮 12시", "noun", "Almorzamos al mediodía.", "정오에 점심을 먹습니다."),
    ("la medianoche", "자정 / 밤 12시", "noun", "A las doce de la medianoche.", "자정 12시에."),
    ("la madrugada", "새벽", "noun", "Me despierto de madrugada.", "새벽에 일어납니다."),
    ("la tarde", "오후", "noun", "Buenas tardes a todos.", "모두 좋은 오후 되세요."),
    ("la mañana", "아침", "noun", "Por la mañana tomo té.", "아침에는 차를 마십니다."),
    ("el caballo", "말", "noun", "Montar a caballo en el campo.", "시골에서 말을 타다."),
    ("la vaca", "소 (암소)", "noun", "La vaca da leche fresca.", "암소는 신선한 우유를 줍니다."),
    ("el toro", "황소", "noun", "El toro bravo español.", "스페인의 용맹한 황소."),
    ("la oveja", "양", "noun", "La lana blanca de la oveja.", "양의 하얀 털."),
    ("el león", "사자", "noun", "El león es el rey de la selva.", "사자는 밀림의 왕이다."),
    ("el tigre", "호랑이", "noun", "Un tigre veloz y fuerte.", "빠르고 강한 호랑이."),
    ("el oso", "곰", "noun", "Un oso pardo en el bosque.", "숲속의 불곰."),
    ("el elefante", "코끼리", "noun", "El elefante tiene orejas grandes.", "코끼리는 귀가 큽니다."),
    ("el mono", "원숭이", "noun", "El mono salta de árbol en árbol.", "원숭이가 나무 사이를 뛰어다녀요."),
    ("el pájaro", "새", "noun", "El pájaro canta al amanecer.", "새가 새벽에 노래합니다."),
    ("el águila", "독수리", "noun", "El águila vuela alto.", "독수리가 높이 납니다."),
    ("el pato", "오리", "noun", "Los patos nadan en el lago.", "오리들이 호수에서 수영해요."),
    ("la gallina", "암탉", "noun", "La gallina pone huevos.", "암탉이 달걀을 낳습니다."),
    ("el ratón", "쥐 / 마우스", "noun", "El gato persigue al ratón.", "고양이가 쥐를 쫓아갑니다."),
    ("la mariposa", "나비", "noun", "Una mariposa de colores vivos.", "화려한 색의 나비."),
    ("la abeja", "꿀벌", "noun", "La abeja produce miel dulce.", "꿀벌이 달콤한 꿀을 만듭니다."),
    ("la mosca", "파리", "noun", "Una mosca molesta.", "성가신 파리 한 마리."),
    ("el mosquito", "모기", "noun", "Me picó un mosquito.", "모기에 물렸어요."),
    ("la araña", "거미", "noun", "Una tela de araña en la pared.", "벽에 걸린 거미줄."),
    ("la camisa", "셔츠", "noun", "Una camisa de lino fresca.", "시원한 린넨 셔츠."),
    ("la camiseta", "티셔츠", "noun", "Una camiseta de algodón.", "면 티셔츠."),
    ("los pantalones", "바지", "noun", "Pantalones cómodos.", "편안한 바지."),
    ("los vaqueros", "청바지", "noun", "Me pongo unos vaqueros azules.", "파란 청바지를 입습니다."),
    ("la falda", "치마", "noun", "Una falda plisada elegante.", "우아한 주름치마."),
    ("el vestido", "드레스 / 원피스", "noun", "Un vestido rojo de fiesta.", "빨간 파티 드레스."),
    ("el abrigo", "코트 / 외투", "noun", "Ponte el abrigo, hace frío.", "코트 입어, 추워."),
    ("la chaqueta", "재킷 / 점퍼", "noun", "Una chaqueta de cuero.", "가죽 재킷."),
    ("el suéter", "스웨터", "noun", "Un suéter de lana cálido.", "따뜻한 울 스웨터."),
    ("los zapatos", "신발", "noun", "Zapatos de vestir negros.", "검은 정장 구두."),
    ("las zapatillas", "운동화 / 슬리퍼", "noun", "Zapatillas para correr.", "러닝화."),
    ("las botas", "부츠", "noun", "Botas para la nieve.", "방한 부츠."),
    ("los calcetines", "양말", "noun", "Un par de calcetines limpios.", "깨끗한 양말 한 켤레."),
    ("el sombrero", "모자 (챙 넓은)", "noun", "Un sombrero de paja veraniego.", "여름용 밀짚모자."),
    ("la gorra", "캡 모자", "noun", "Una gorra deportiva.", "스포츠 캡 모자."),
    ("la bufanda", "목도리", "noun", "Una bufanda de lana suave.", "부드러운 울 목도리."),
    ("los guantes", "장갑", "noun", "Guantes para el invierno.", "겨울용 장갑."),
    ("el cinturón", "벨트 / 허리띠", "noun", "Ajusta el cinturón.", "허리띠를 조이세요."),
    ("las gafas", "안경", "noun", "Gafas para leer.", "독서용 안경."),
    ("las gafas de sol", "선글라스", "noun", "Gafas de sol polarizadas.", "편광 선글라스."),
    ("el paraguas", "우산", "noun", "Lleva un paraguas por si llueve.", "비 올지 모르니 우산 챙겨."),
    ("el bolsillo", "주머니", "noun", "Metí las llaves en el bolsillo.", "열쇠를 주머니에 넣었어요."),
    ("el botón", "단추 / 버튼", "noun", "Se cayó un botón.", "단추가 하나 떨어졌어요."),
    ("la cremallera", "지퍼", "noun", "Sube la cremallera.", "지퍼를 올리세요."),
    ("la sartén", "프라이팬", "noun", "Calienta aceite en la sartén.", "팬에 기름을 두르세요."),
    ("la olla", "냄비", "noun", "Una olla de sopa caliente.", "뜨거운 수프 냄비."),
    ("el horno", "오븐", "noun", "Pan horneado en horno de leña.", "화덕 오븐에 구운 빵."),
    ("el microondas", "전자레인지", "noun", "Calienta la comida al microondas.", "전자레인지로 음식을 데우세요."),
    ("la nevera", "냉장고", "noun", "Guarda la leche en la nevera.", "우유를 냉장고에 넣으세요."),
    ("el congelador", "냉동고", "noun", "Helado en el congelador.", "냉동실 안의 아이스크림."),
    ("la lavadora", "세탁기", "noun", "Puse la lavadora.", "세탁기를 돌렸어요."),
    ("el lavavajillas", "식기세척기", "noun", "Platos limpios en el lavavajillas.", "식기세척기의 깨끗한 접시들."),
    ("el jabón", "비누", "noun", "Lávate con agua y jabón.", "비누와 물로 씻으세요."),
    ("el champú", "샴푸", "noun", "Champú con aroma a coco.", "코코넛 향 샴푸."),
    ("la toalla", "수건", "noun", "Sécate con la toalla.", "수건으로 물기를 닦으세요."),
    ("el cepillo", "칫솔 / 빗", "noun", "Cepillo de dientes nuevo.", "새 칫솔."),
    ("la pasta de dientes", "치약", "noun", "Pasta de dientes con flúor.", "불소 치약."),
    ("la sábana", "침대 시트", "noun", "Sábanas limpias de algodón.", "깨끗한 면 시트."),
    ("la almohada", "베개", "noun", "Una almohada cómoda y suave.", "푹신하고 편안한 베개."),
    ("la manta", "담요 / 이불", "noun", "Tápate con la manta.", "담요를 덮으세요."),
    ("la cortina", "커튼", "noun", "Abre las cortinas para que entre sol.", "햇살이 들어오게 커튼을 치세요."),
    ("la alfombra", "카펫 / 양탄자", "noun", "Una alfombra persa en el salón.", "거실의 페르시아 카펫."),
    ("la estrella", "별", "noun", "Una noche llena de estrellas.", "별이 총총한 밤."),
    ("el planeta", "행성", "noun", "El planeta Tierra.", "행성 지구."),
    ("el desierto", "사막", "noun", "El desierto del Sahara.", "사하라 사막."),
    ("la selva", "밀림 / 정글", "noun", "La selva amazónica.", "아마존 밀림."),
    ("la cascada", "폭포", "noun", "Una cascada impresionante.", "장엄한 폭포."),
    ("la cueva", "동굴", "noun", "Una cueva oscura y profunda.", "어둡고 깊은 동굴."),
    ("la ola", "파도", "noun", "Olas gigantes en el mar.", "바다의 거대한 파도."),
    ("la tormenta", "폭풍 / 뇌우", "noun", "Se acerca una tormenta fuerte.", "강한 폭풍이 다가옵니다."),
    ("el trueno", "천둥", "noun", "Sonó un trueno fuerte.", "큰 천둥이 쳤습니다."),
    ("el relámpago", "번개", "noun", "Un relámpago iluminó el cielo.", "번개가 하늘을 밝혔어요."),
    ("el arcoíris", "무지개", "noun", "Un arcoíris después de la lluvia.", "비 온 뒤의 무지개."),
    ("la niebla", "안개", "noun", "Mucha niebla en la carretera.", "도로에 짙은 안개."),

    # 12개월 (Meses del año)
    ("enero", "1월", "noun", "En enero hace frío.", "1월에는 날씨가 춥습니다."),
    ("febrero", "2월", "noun", "Febrero es el mes más corto.", "2월은 가장 짧은 달입니다."),
    ("marzo", "3월", "noun", "En marzo llega la primavera.", "3월에 봄이 찾아옵니다."),
    ("abril", "4월", "noun", "Abril suele ser lluvioso.", "4월은 보통 비가 자주 와요."),
    ("mayo", "5월", "noun", "En mayo florecen las rosas.", "5월에는 장미가 핍니다."),
    ("junio", "6월", "noun", "En junio comienza el verano.", "6월에 여름이 시작됩니다."),
    ("julio", "7월", "noun", "Julio es ideal para la playa.", "7월은 해변에 가기 딱 좋아요."),
    ("agosto", "8월", "noun", "En agosto tenemos vacaciones.", "8월에 휴가가 있습니다."),
    ("septiembre", "9월", "noun", "En septiembre empiezan las clases.", "9월에 개학을 합니다."),
    ("octubre", "10월", "noun", "Octubre trae hojas doradas.", "10월은 황금빛 낙엽을 데려옵니다."),
    ("noviembre", "11월", "noun", "Noviembre es fresco y tranquilo.", "11월은 선선하고 고요합니다."),
    ("diciembre", "12월", "noun", "En diciembre celebramos la Navidad.", "12월에 성탄절을 기념합니다."),

    # 필수 기초 숫자 (Números básicos)
    ("cero", "영 (0)", "noun", "Empieza desde cero.", "0부터 시작하세요."),
    ("uno", "하나 (1)", "noun", "Número uno en ventas.", "판매 1위."),
    ("dos", "둘 (2)", "noun", "Dos billetes, por favor.", "티켓 두 장 부탁합니다."),
    ("tres", "셋 (3)", "noun", "Tres veces al día.", "하루에 세 번."),
    ("cuatro", "넷 (4)", "noun", "Cuatro estaciones del año.", "한 해의 사계절."),
    ("cinco", "다섯 (5)", "noun", "Faltan cinco minutos.", "5분 남았습니다."),
    ("seis", "여섯 (6)", "noun", "A las seis de la tarde.", "오후 6시에."),
    ("siete", "일곱 (7)", "noun", "Los siete días de la semana.", "일주일의 7일."),
    ("ocho", "여덟 (8)", "noun", "Duermo ocho horas diarias.", "하루 8시간씩 잡니다."),
    ("nueve", "아홉 (9)", "noun", "El tren sale a las nueve.", "기차는 9시에 출발해요."),
    ("diez", "열 (10)", "noun", "Una nota de diez sobre diez.", "10점 만점에 10점."),
    ("cien", "백 (100)", "noun", "Cien por ciento seguro.", "100퍼센트 확실해요."),
    ("mil", "천 (1,000)", "noun", "Mil gracias por todo.", "모든 것에 천 번 감사드려요."),
    ("millón", "백만 (1,000,000)", "noun", "Un millón de sueños.", "백만 개의 꿈."),

    # 여행, 숙소, 공항, 병원 필수 명사 (Viajes, Hotel y Salud)
    ("el menú", "메뉴판 / 식단", "noun", "¿Me trae el menú, por favor?", "메뉴판 좀 가져다주시겠어요?"),
    ("la farmacia", "약국", "noun", "¿Dónde hay una farmacia cerca?", "근처에 약국이 어디 있나요?"),
    ("la pastilla", "알약", "noun", "Toma una pastilla con agua.", "물과 함께 알약 한 알을 드세요."),
    ("la tirita", "반창고", "noun", "Ponte una tirita en el dedo.", "손가락에 반창고를 붙이세요."),
    ("el vendaje", "붕대", "noun", "Un vendaje en el tobillo.", "발목에 감은 붕대."),
    ("la ambulancia", "구급차", "noun", "Llama a la ambulancia.", "구급차를 부르세요."),
    ("las urgencias", "응급실", "noun", "Vamos a urgencias del hospital.", "병원 응급실로 갑시다."),
    ("la aduana", "세관", "noun", "Pasar por el control de aduana.", "세관 심사를 통과하다."),
    ("la tarjeta de embarque", "탑승권", "noun", "Muestre su tarjeta de embarque.", "탑승권을 보여주세요."),
    ("la puerta de embarque", "탑승 게이트", "noun", "Embarque por la puerta cuatro.", "4번 게이트로 탑승하세요."),
    ("la salida", "출구 / 출발", "noun", "Salida de emergencia.", "비상구."),
    ("la entrada", "입구 / 입장권", "noun", "Comprar una entrada de cine.", "영화 입장권을 사다."),
    ("la llegada", "도착", "noun", "Hora prevista de llegada.", "도착 예정 시각."),
    ("la consigna", "물품보관소", "noun", "Dejo la maleta en la consigna.", "물품보관소에 가방을 맡깁니다."),
    ("el consulado", "영사관", "noun", "Contacte con el consulado.", "영사관에 연락하세요."),
    ("la embajada", "대사관", "noun", "La embajada de Corea en España.", "주스페인 한국 대사관."),
    ("la comisaría", "경찰서", "noun", "Hacer la denuncia en comisaría.", "경찰서에 신고서를 작성하다."),
    ("el carné", "신분증", "noun", "Carné de identidad.", "신분증."),
    ("la licencia", "면허증 / 허가", "noun", "Licencia de conducir internacional.", "국제운전면허증."),
    ("el seguro", "보험", "noun", "Seguro de viaje internacional.", "해외여행자보험."),
    ("la habitación doble", "2인실 (더블룸)", "noun", "Una habitación doble con vistas.", "전망 좋은 더블룸."),
    ("la habitación individual", "1인실 (싱글룸)", "noun", "Quiero una habitación individual.", "싱글룸을 원합니다."),
    ("el aire acondicionado", "에어컨", "noun", "El aire acondicionado funciona bien.", "에어컨이 잘 작동해요."),
    ("la calefacción", "난방", "noun", "Enciende la calefacción.", "난방을 켜세요."),
    ("el wifi", "와이파이", "noun", "¿Cuál es la contraseña del wifi?", "와이파이 비밀번호가 뭐예요?"),
    ("la contraseña", "비밀번호", "noun", "Escribe tu contraseña secreta.", "비밀번호를 입력하세요."),
    ("la dirección", "주소 / 방향", "noun", "¿Cuál es la dirección del hotel?", "호텔 주소가 어떻게 되나요?"),
    ("el código postal", "우편번호", "noun", "Indica el código postal.", "우편번호를 적어주세요."),
    ("el piso", "아파트 / 층", "noun", "Vivo en el cuarto piso.", "4층에 살고 있습니다."),
    ("el buzón", "우체통", "noun", "Echa la carta en el buzón.", "편지를 우체통에 넣으세요."),
    ("la oficina de correos", "우체국", "noun", "Voy a la oficina de correos.", "우체국에 갑니다."),
    ("el paquete", "소포 / 택배", "noun", "Recibí un paquete hoy.", "오늘 택배를 받았습니다."),
    ("once", "열하나 (11)", "noun", "Once jugadores en el campo.", "경기장 위의 11명의 선수."),
    ("doce", "열둘 (12)", "noun", "Las doce del mediodía.", "낮 12시."),
    ("trece", "열셋 (13)", "noun", "Número trece de la suerte.", "행운의 13번."),
    ("catorce", "열넷 (14)", "noun", "Catorce días de vacaciones.", "14일간의 휴가."),
    ("quince", "열다섯 (15)", "noun", "Quince minutos de descanso.", "15분의 휴식."),
    ("dieciséis", "열여섯 (16)", "noun", "Dieciséis años cumplidos.", "만 16세."),
    ("diecisiete", "열일곱 (17)", "noun", "El autobús diecisiete.", "17번 버스."),
    ("dieciocho", "열여덟 (18)", "noun", "Mayor de dieciocho años.", "18세 이상."),
    ("diecinueve", "열아홉 (19)", "noun", "Página diecinueve.", "19페이지."),
    ("veinte", "스물 (20)", "noun", "Veinte euros en el bolsillo.", "주머니에 20유로."),
    ("treinta", "서른 (30)", "noun", "Treinta días tiene noviembre.", "11월은 30일까지 있어요."),
    ("cuarenta", "마흔 (40)", "noun", "Cuarenta grados de calor.", "섭씨 40도의 무더위."),
    ("cincuenta", "쉰 (50)", "noun", "Cincuenta por ciento de descuento.", "50퍼센트 할인."),
    ("sesenta", "예순 (60)", "noun", "Sesenta minutos en una hora.", "1시간은 60분."),
    ("setenta", "일흔 (70)", "noun", "Setenta años de historia.", "70년의 역사."),
    ("ochenta", "여든 (80)", "noun", "Ochenta kilómetros por hora.", "시속 80킬로미터."),
    ("noventa", "아흔 (90)", "noun", "Noventa minutos de partido.", "90분간의 경기."),
    ("la copa", "와인잔 / 컵", "noun", "Una copa de vino tinto.", "레드와인 한 잔."),
    ("la jarra", "물주전자 / 피처", "noun", "Una jarra de agua fresca.", "시원한 물 한 주전자."),
    ("el tapón", "마개 / 뚜껑", "noun", "Abre el tapón de la botella.", "병뚜껑을 여세요."),
    ("el abrelatas", "캔따개", "noun", "¿Tienes un abrelatas?", "캔따개 있나요?"),
    ("el sacacorchos", "와인 오프너", "noun", "Usa el sacacorchos.", "와인 오프너를 사용하세요."),
    ("el mantel", "식탁보", "noun", "Un mantel blanco y limpio.", "하얗고 깨끗한 식탁보."),
    ("la vela", "양초 / 촛불", "noun", "Cena a la luz de las velas.", "촛불을 켠 저녁 식사."),
    ("la tarjeta de metro", "교통카드", "noun", "Recarga tu tarjeta de metro.", "교통카드를 충전하세요."),
]

# 3. PREPOSITIONS, CONJUNCTIONS, ADVERBS & QUESTION WORDS (110+)
PREPS_AND_CONJS = [
    ("de", "~의 / ~로부터", "prep", "Soy de Corea del Sur.", "저는 한국에서 왔습니다."),
    ("en", "~에 / ~안에", "prep", "Vivo en Madrid.", "마드리드에 살아요."),
    ("a", "~로 / ~에게", "prep", "Voy a la escuela.", "학교에 갑니다."),
    ("por", "~때문에 / ~을 통해", "prep", "Gracias por tu ayuda.", "도와줘서 고마워."),
    ("para", "~를 위해 / ~을 향해", "prep", "Este libro es para ti.", "이 책은 너를 위한 거야."),
    ("con", "~와 함께", "prep", "Café con leche.", "우유 넣은 커피."),
    ("sin", "~없이", "prep", "Café sin azúcar.", "설탕 없는 커피."),
    ("sobre", "~위에 / ~에 대하여", "prep", "Hablamos sobre el futuro.", "우리는 미래에 대해 이야기해요."),
    ("entre", "~사이에", "prep", "Entre tú y yo.", "너와 나 사이에."),
    ("hasta", "~까지", "prep", "Hasta mañana.", "내일 만나요."),
    ("desde", "~부터 (기점)", "prep", "Desde ayer no como nada.", "어제부터 아무것도 안 먹었어요."),
    ("hacia", "~을 향하여", "prep", "Camina hacia la luz.", "빛을 향해 걸어가세요."),
    ("contra", "~에 대항하여", "prep", "Luchar contra el tiempo.", "시간과 맞서 싸우다."),
    ("bajo", "~아래에", "prep", "Bajo las estrellas.", "별빛 아래에서."),
    ("ante", "~앞에 / ~에 직면하여", "prep", "Ante esta situación.", "이러한 상황 앞에서."),
    ("tras", "~뒤에 / ~후에", "prep", "Tras un largo viaje.", "긴 여행 끝에."),
    ("según", "~에 따르면", "prep", "Según el pronóstico.", "일기예보에 따르면."),
    ("pero", "하지만 / 그러나", "prep", "Es difícil, pero divertido.", "어렵지만 재미있어요."),
    ("y", "그리고 / 와", "prep", "Pan y mantequilla.", "빵과 버터."),
    ("o", "또는 / 혹은", "prep", "¿Té o café?", "차 드실래요, 커피 드실래요?"),
    ("porque", "왜냐하면", "prep", "Estudio porque quiero viajar.", "여행하고 싶어서 공부해요."),
    ("si", "만약 ~라면", "prep", "Si tienes tiempo, ven.", "시간 있으면 놀러 와."),
    ("aunque", "비록 ~일지라도", "prep", "Aunque llueva, saldré.", "비가 올지라도 나갈 거야."),
    ("cuando", "~할 때", "prep", "Cuando era niño.", "내가 어렸을 때."),
    ("como", "~처럼 / ~로서", "prep", "Canta como un ángel.", "천사처럼 노래해요."),
    ("que", "~하는 것 / 관계대명사", "prep", "El libro que compré.", "내가 산 책."),
    ("donde", "~하는 곳", "prep", "La casa donde vivo.", "내가 사는 집."),
    ("mientras", "~하는 동안에", "prep", "Escucho música mientras estudio.", "공부하는 동안 음악을 들어요."),
    ("así que", "그래서", "prep", "Estaba cansado, así que dormí.", "피곤해서 잠을 잤어요."),
    ("sin embargo", "그러나 / 그럼에도 불구하고", "prep", "Es caro, sin embargo lo quiero.", "비싸지만, 그래도 갖고 싶어요."),
    ("por eso", "그 때문에", "prep", "Por eso llegué tarde.", "그래서 늦었습니다."),
    ("además", "게다가 / 또한", "prep", "Es inteligente, además es amable.", "똑똑하고 게다가 친절해요."),
    ("por lo tanto", "따라서", "prep", "Pienso, por lo tanto existo.", "나는 생각한다, 고로 존재한다."),
    ("en cambio", "반면에", "prep", "A mí me gusta, en cambio a él no.", "난 좋은데 반면에 그는 싫어해요."),
    ("qué", "무엇 / 무슨", "prep", "¿Qué quieres hacer hoy?", "오늘 뭐 하고 싶니?"),
    ("quién", "누구", "prep", "¿Quién es esa persona?", "저분은 누구인가요?"),
    ("cuál", "어느 것 / 어떤", "prep", "¿Cuál prefieres?", "어느 것이 더 좋니?"),
    ("cuánto", "얼마나 (양)", "prep", "¿Cuánto cuesta esto?", "이것 얼마인가요?"),
    ("cuándo", "언제", "prep", "¿Cuándo nos vemos?", "우리 언제 볼까?"),
    ("dónde", "어디에", "prep", "¿Dónde está la estación?", "역이 어디에 있나요?"),
    ("cómo", "어떻게", "prep", "¿Cómo estás?", "어떻게 지내세요?"),
    ("por qué", "왜", "prep", "¿Por qué estudias español?", "왜 스페인어를 공부하니?"),
    ("hoy", "오늘", "prep", "Hoy hace un día soleado.", "오늘은 맑은 날씨예요."),
    ("ayer", "어제", "prep", "Ayer te vi en el parque.", "어제 공원에서 널 봤어."),
    ("mañana", "내일 / 아침", "prep", "Hasta mañana por la mañana.", "내일 아침에 만나요."),
    ("anoche", "어젯밤", "prep", "Anoche soñé contigo.", "어젯밤 너의 꿈을 꿨어."),
    ("ahora", "지금", "prep", "Ahora o nunca.", "지금 아니면 결코 없다."),
    ("luego", "나중에", "prep", "Hasta luego.", "나중에 봐요."),
    ("después", "나중에 / 뒤에", "prep", "Después de comer.", "식사한 후에."),
    ("antes", "전에", "prep", "Antes de salir.", "나가기 전에."),
    ("pronto", "곧 / 일찍", "prep", "Nos vemos pronto.", "곧 다시 만나요."),
    ("tarde", "늦게 / 오후", "prep", "Llegas muy tarde.", "너무 늦게 왔어."),
    ("temprano", "일찍", "prep", "Me despierto temprano.", "일찍 일어납니다."),
    ("siempre", "항상", "prep", "Siempre te recuerdo.", "항상 널 기억해."),
    ("nunca", "결코 ~않다", "prep", "Nunca te olvidaré.", "절대 널 잊지 않을게."),
    ("jamás", "결코 / 전혀", "prep", "Jamás me rindo.", "결코 포기하지 않아요."),
    ("a veces", "가끔", "prep", "A veces como fuera.", "가끔 외식을 합니다."),
    ("ya", "이미 / 벌써", "prep", "Ya terminé mi trabajo.", "이미 일을 끝냈어요."),
    ("todavía", "아직 / 여전히", "prep", "Todavía tengo dudas.", "아직 의문이 남았어요."),
    ("aún", "아직 / 여전히", "prep", "Aún no ha llegado.", "아직 도착하지 않았어요."),
    ("aquí", "여기", "prep", "Ven aquí, por favor.", "여기로 오세요."),
    ("allí", "저기", "prep", "Mira allí.", "저기를 보세요."),
    ("allá", "저 너머 / 저기", "prep", "Más allá del mar.", "바다 저 너머에."),
    ("cerca", "가까이", "prep", "La tienda está muy cerca.", "가게가 아주 가까워요."),
    ("lejos", "멀리", "prep", "Vivo lejos de aquí.", "여기서 멀리 살아요."),
    ("arriba", "위에 / 위로", "prep", "Mira arriba.", "위를 보세요."),
    ("abajo", "아래에 / 아래로", "prep", "Baja abajo.", "아래로 내려오세요."),
    ("delante", "앞에", "prep", "Ponte delante de mí.", "내 앞에 서세요."),
    ("detrás", "뒤에", "prep", "Está detrás de ti.", "네 뒤에 있어."),
    ("dentro", "안에", "prep", "Entra dentro de la casa.", "집 안으로 들어오세요."),
    ("fuera", "밖에", "prep", "Hace frío afuera.", "밖은 추워요."),
    ("al lado", "옆에", "prep", "Siéntate a mi lado.", "내 옆에 앉으세요."),
    ("enfrente", "맞은편에", "prep", "Vive enfrente de mi casa.", "우리 집 맞은편에 살아요."),
    ("alrededor", "주변에", "prep", "Viaje alrededor del mundo.", "세계 일주 여행."),
    ("bien", "잘 / 좋은", "prep", "Todo está muy bien.", "모든 것이 아주 좋아요."),
    ("mal", "나쁘게 / 잘못", "prep", "Me siento mal hoy.", "오늘 몸 상태가 안 좋아요."),
    ("mucho", "많이 / 많은", "prep", "Muchas gracias.", "정말 감사합니다."),
    ("poco", "조금 / 적은", "prep", "Hablo un poco.", "조금 말할 수 있어요."),
    ("muy", "매우 / 아주", "prep", "Es muy inteligente.", "그는 매우 똑똑합니다."),
    ("más", "더 / 더 많은", "prep", "Un poco más de tiempo.", "시간을 조금만 더 줘."),
    ("menos", "덜 / 덜한", "prep", "Más o menos.", "대충 / 그럭저럭."),
    ("tan", "그렇게 / 너무", "prep", "Es tan bonito.", "너무나 아름다워요."),
    ("tanto", "그렇게 많이", "prep", "Te quiero tanto.", "널 너무나 많이 사랑해."),
    ("bastante", "꽤 / 충분히", "prep", "Es bastante grande.", "꽤 큽니다."),
    ("demasiado", "너무 많이 / 지나치게", "prep", "Cuesta demasiado caro.", "지나치게 비싸요."),
    ("casi", "거의", "prep", "Casi se me olvida.", "하마터면 잊을 뻔했어."),
    ("apenas", "간신히 / 겨우", "prep", "Apenas puedo oírte.", "네 목소리가 거의 안 들려."),
    ("sólo", "오직 / 단지", "prep", "Sólo tengo cinco euros.", "오직 5유로만 있어요."),
    ("solamente", "단지", "prep", "Es solamente un rumor.", "단지 소문일 뿐이야."),
    ("también", "~도 / 역시", "prep", "Yo también voy.", "나도 갈래."),
    ("tampoco", "~도 아니다", "prep", "Yo tampoco lo sé.", "나도 그것을 잘 몰라."),
    ("quizás", "아마도", "prep", "Quizás mañana.", "아마 내일일 거야."),
    ("tal vez", "어쩌면", "prep", "Tal vez tengas razón.", "어쩌면 네 말이 맞을지도 몰라."),
    ("seguramente", "분명히", "prep", "Seguramente vendrá.", "그는 분명히 올 거예요."),
    ("claramente", "분명하게", "prep", "Explica claramente.", "명확하게 설명하세요."),
    ("rápidamente", "빨리", "prep", "Corre rápidamente.", "빨리 달리세요."),
    ("lentamente", "천천히", "prep", "Habla lentamente, por favor.", "천천히 말씀해 주세요."),
    ("fácilmente", "쉽게", "prep", "Lo resolvió fácilmente.", "그는 쉽게 해결했어요."),
    ("difícilmente", "어렵게 / 거의 ~않다", "prep", "Difícilmente lo creo.", "도저히 믿기지 않아요."),
    ("afortunadamente", "다행히도", "prep", "Afortunadamente todo salió bien.", "다행히 모든 게 잘 풀렸어."),
    ("desafortunadamente", "불행하게도", "prep", "Desafortunadamente no puedo ir.", "안타깝게도 갈 수 없어요."),
    ("realmente", "정말로", "prep", "Es realmente hermoso.", "정말로 아름답습니다."),
    ("verdaderamente", "진실로", "prep", "Te amo verdaderamente.", "진심으로 널 사랑해."),
    ("especialmente", "특별히", "prep", "Me gusta, especialmente en verano.", "특히 여름에 좋아해요."),
    ("generalmente", "일반적으로", "prep", "Generalmente ceno temprano.", "보통 저녁을 일찍 먹어요."),
    ("normalmente", "평상시에는", "prep", "Normalmente tomo café solo.", "평소에는 블랙커피를 마셔요."),
    ("exactamente", "정확히", "prep", "Son exactamente las cinco.", "정확히 5시입니다."),
    ("finalmente", "마침내", "prep", "Finalmente llegamos a casa.", "마침내 집에 도착했어요."),
    ("incluso", "심지어 / ~조차", "prep", "Incluso él vino a verme.", "심지어 그도 날 보러 왔어."),
    ("salvo", "~을 제외하고", "prep", "Todos fueron salvo Juan.", "후안을 제외하고 모두 갔어요."),
    ("excepto", "~을 제외하고", "prep", "Abierto todos los días excepto lunes.", "월요일 제외 매일 영업."),
]

# 4. ADJECTIVES AND COMMON PHRASES (190+)
ADJECTIVES_AND_PHRASES = [
    ("bueno", "좋은", "adj", "Un buen día.", "좋은 날."),
    ("malo", "나쁜", "adj", "No es una mala idea.", "나쁜 생각은 아니에요."),
    ("grande", "큰", "adj", "Una casa grande.", "큰 집."),
    ("pequeño", "작은", "adj", "Un perro pequeño.", "작은 개."),
    ("nuevo", "새로운", "adj", "Tengo un teléfono nuevo.", "새 전화기가 생겼어요."),
    ("viejo", "오래된 / 늙은", "adj", "Un amigo viejo.", "오랜 친구."),
    ("joven", "젊은", "adj", "Una persona joven y llena de energía.", "에너지 넘치는 젊은이."),
    ("alto", "높은 / 키 큰", "adj", "Un hombre muy alto.", "키가 아주 큰 남자."),
    ("bajo", "낮은 / 키 작은", "adj", "Un precio bajo.", "낮은 가격."),
    ("largo", "긴", "adj", "Un camino largo.", "긴 길."),
    ("corto", "짧은", "adj", "Una falda corta.", "짧은 치마."),
    ("fácil", "쉬운", "adj", "El examen fue fácil.", "시험이 쉬웠어요."),
    ("difícil", "어려운", "adj", "Aprender idiomas no es difícil.", "언어 배우기는 어렵지 않아요."),
    ("rápido", "빠른", "adj", "Un tren muy rápido.", "매우 빠른 기차."),
    ("lento", "느린", "adj", "El tráfico está lento.", "교통 흐름이 느려요."),
    ("feliz", "행복한", "adj", "¡Feliz cumpleaños!", "생일 축하합니다!"),
    ("triste", "슬픈", "adj", "Una canción triste.", "슬픈 노래."),
    ("rico", "맛있는 / 부유한", "adj", "La comida está muy rica.", "음식이 정말 맛있어요."),
    ("pobre", "가난한 / 불쌍한", "adj", "Pobre hombre.", "불쌍한 사람."),
    ("caro", "비싼", "adj", "Este reloj es muy caro.", "이 시계는 너무 비싸요."),
    ("barato", "저렴한", "adj", "Una ropa bonita y barata.", "예쁘고 저렴한 옷."),
    ("limpio", "깨끗한", "adj", "Una habitación limpia.", "깨끗한 방."),
    ("sucio", "더러운", "adj", "Los zapatos están sucios.", "신발이 더러워요."),
    ("caliente", "뜨거운", "adj", "Sopa caliente.", "뜨거운 수프."),
    ("frío", "차가운 / 추운", "adj", "Agua fría con hielo.", "얼음 띄운 찬물."),
    ("fresco", "신선한 / 시원한", "adj", "Fruta fresca.", "신선한 과일."),
    ("seco", "마른 / 건조한", "adj", "Clima seco.", "건조한 기후."),
    ("mojado", "젖은", "adj", "El suelo está mojado.", "바닥이 젖어 있어요."),
    ("lleno", "가득 찬", "adj", "El vaso está lleno.", "잔이 가득 찼어요."),
    ("vacío", "비어 있는", "adj", "Una caja vacía.", "빈 상자."),
    ("fuerte", "강한 / 튼튼한", "adj", "Un viento fuerte.", "강한 바람."),
    ("débil", "약한", "adj", "Me siento débil hoy.", "오늘 몸이 약해진 기분이에요."),
    ("inteligente", "똑똑한", "adj", "Un alumno muy inteligente.", "매우 똑똑한 학생."),
    ("tonto", "바보 같은", "adj", "No digas cosas tontas.", "바보 같은 소리 하지 마."),
    ("amable", "친절한", "adj", "Gracias por ser tan amable.", "친절하게 대해주셔서 감사해요."),
    ("simpático", "호감 가는 / 친절한", "adj", "Tu hermano es simpático.", "너의 남동생은 호감형이야."),
    ("antipático", "비호감의 / 불친절한", "adj", "Un dependiente antipático.", "불친절한 점원."),
    ("hermoso", "아름다운", "adj", "Un paisaje hermoso.", "아름다운 풍경."),
    ("bello", "아름다운", "adj", "La vida es bella.", "인생은 아름다워."),
    ("bonito", "예쁜", "adj", "Qué bonito vestido.", "정말 예쁜 드레스네요."),
    ("feo", "못생긴", "adj", "Un cuadro feo.", "못생긴 그림."),
    ("claro", "밝은 / 명확한", "adj", "Una respuesta clara.", "명확한 대답."),
    ("oscuro", "어두운", "adj", "Una noche oscura.", "어두운 밤."),
    ("abierto", "열린", "adj", "La tienda está abierta.", "가게 문이 열려 있어요."),
    ("cerrado", "닫힌", "adj", "El banco está cerrado.", "은행 문이 닫혔어요."),
    ("libre", "자유로운 / 한가한", "adj", "¿Estás libre esta tarde?", "오늘 오후에 시간 되니?"),
    ("ocupado", "바쁜", "adj", "Estoy muy ocupado hoy.", "오늘 너무 바빠요."),
    ("seguro", "안전한 / 확신하는", "adj", "Estoy seguro de ello.", "그것에 대해 확신해요."),
    ("peligroso", "위험한", "adj", "Es peligroso cruzar aquí.", "여기서 길을 건너는 것은 위험해요."),
    ("importante", "중요한", "adj", "Una decisión importante.", "중요한 결정."),
    ("interesante", "흥미로운", "adj", "Un tema muy interesante.", "매우 흥미로운 주제."),
    ("aburrido", "지루한", "adj", "Una clase aburrida.", "지루한 수업."),
    ("divertido", "재미있는", "adj", "Un juego divertido.", "재미있는 게임."),
    ("cansado", "피곤한", "adj", "Estoy cansado después del trabajo.", "퇴근 후 피곤해요."),
    ("tranquilo", "조용한 / 평온한", "adj", "Un pueblo tranquilo.", "조용한 시골 마을."),
    ("ruidoso", "시끄러운", "adj", "Una calle ruidosa.", "시끄러운 거리."),
    ("pesado", "무거운", "adj", "Una maleta pesada.", "무거운 캐리어."),
    ("ligero", "가벼운", "adj", "Una mochila ligera.", "가벼운 배낭."),
    ("duro", "단단한 / 힘든", "adj", "Un trabajo duro.", "힘든 일."),
    ("blando", "부드러운 / 푹신한", "adj", "Pan blando.", "부드러운 빵."),
    ("suave", "부드러운 (촉감)", "adj", "Piel suave.", "부드러운 피부."),
    ("áspero", "거친", "adj", "Superficie áspera.", "거친 표면."),
    ("dulce", "달콤한", "adj", "Un postre dulce.", "달콤한 디저트."),
    ("salado", "짠", "adj", "Sopa demasiado salada.", "너무 짠 수프."),
    ("amargo", "쓴", "adj", "Café amargo.", "쓴 커피."),
    ("ácido", "신 / 산성의", "adj", "Limón ácido.", "신 레몬."),
    ("picante", "매운", "adj", "Comida picante coreana.", "매운 한국 음식."),
    ("delicioso", "매우 맛있는", "adj", "¡Qué delicioso!", "정말 맛있어요!"),
    ("sabroso", "풍미 있는", "adj", "Un vino sabroso.", "풍미 가득한 와인."),
    ("sano", "건강한", "adj", "Una vida sana.", "건강한 삶."),
    ("enfermo", "아픈", "adj", "El niño está enfermo.", "아이가 아파요."),
    ("primero", "첫 번째의", "adj", "El primer paso.", "첫 번째 발걸음."),
    ("segundo", "두 번째의", "adj", "El segundo piso.", "2층."),
    ("tercero", "세 번째의", "adj", "El tercer día.", "세 번째 날."),
    ("último", "마지막의", "adj", "La última oportunidad.", "마지막 기회."),
    ("mismo", "같은", "adj", "El mismo lugar.", "같은 장소."),
    ("diferente", "다른", "adj", "Una cultura diferente.", "다른 문화."),
    ("igual", "같은 / 동등한", "adj", "Todos somos iguales.", "우리는 모두 평등합니다."),
    ("perfecto", "완벽한", "adj", "Un día perfecto.", "완벽한 하루."),
    ("correcto", "올바른", "adj", "La respuesta correcta.", "올바른 정답."),
    ("incorrecto", "틀린", "adj", "Opción incorrecta.", "틀린 선택지."),
    ("verdadero", "참된 / 진짜의", "adj", "Un amigo verdadero.", "진정한 친구."),
    ("falso", "거짓의 / 가짜의", "adj", "Un rumor falso.", "거짓 소문."),
    ("útil", "유용한", "adj", "Un consejo útil.", "유용한 조언."),
    ("inútil", "쓸모없는", "adj", "Es inútil quejarse.", "불평해봐야 소용없어요."),
    ("cómodo", "편안한", "adj", "Una cama cómoda.", "편안한 침대."),
    ("incómodo", "불편한", "adj", "Un asiento incómodo.", "불편한 좌석."),
    ("famoso", "유명한", "adj", "Un cantante famoso.", "유명한 가수."),
    ("desconocido", "알려지지 않은", "adj", "Un autor desconocido.", "알려지지 않은 작가."),
    ("popular", "인기 있는", "adj", "Una canción muy popular.", "매우 인기 있는 노래."),
    ("común", "흔한 / 공통의", "adj", "Un error común.", "흔한 실수."),
    ("raro", "이상한 / 드문", "adj", "Un pájaro raro.", "희귀한 새."),
    ("extraño", "이상한 / 낯선", "adj", "Una voz extraña.", "낯선 목소리."),
    ("rojo", "빨간색의", "adj", "Una rosa roja.", "빨간 장미."),
    ("azul", "파란색의", "adj", "El cielo azul.", "파란 하늘."),
    ("verde", "초록색의", "adj", "Hierba verde fresca.", "싱그러운 초록 잔디."),
    ("amarillo", "노란색의", "adj", "El sol amarillo.", "노란 태양."),
    ("blanco", "하얀색의", "adj", "Nieve blanca pura.", "순백의 하얀 눈."),
    ("negro", "검은색의", "adj", "Un café solo negro.", "진한 블랙커피."),
    ("gris", "회색의", "adj", "Un día gris y nublado.", "흐리고 회색빛인 날."),
    ("marrón", "갈색의", "adj", "Ojos color marrón.", "갈색 눈동자."),
    ("rosa", "분홍색의", "adj", "Flores de color rosa.", "분홍빛 꽃들."),
    ("morado", "보라색의", "adj", "Uvas moradas dulces.", "달콤한 보라색 포도."),
    ("naranja", "주황색의", "adj", "Una camiseta naranja brillante.", "밝은 주황색 티셔츠."),
    ("paciente", "참을성 있는", "adj", "Un maestro muy paciente.", "매우 참을성 있는 선생님."),
    ("impaciente", "조급한", "adj", "No seas impaciente.", "조급해하지 마세요."),
    ("valiente", "용감한", "adj", "Un héroe valiente.", "용감한 영웅."),
    ("cobarde", "겁쟁이의 / 비겁한", "adj", "No seas cobarde.", "비겁하게 굴지 마."),
    ("generoso", "관대한 / 후한", "adj", "Una persona muy generosa.", "매우 너그러운 사람."),
    ("tacaño", "구두쇠의 / 인색한", "adj", "Un hombre tacaño.", "인색한 남자."),
    ("sincero", "솔직한 / 진실한", "adj", "Una opinion sincera.", "솔직한 의견."),
    ("optimista", "낙천적인", "adj", "Mantén una actitud optimista.", "낙천적인 태도를 가지세요."),
    ("pesimista", "비관적인", "adj", "No seas tan pesimista.", "너무 비관적으로 생각하지 마."),
    ("educado", "예의 바른", "adj", "Un joven muy educado.", "매우 예의 바른 청년."),
    ("maleducado", "무례한 / 버릇없는", "adj", "Un comportamiento maleducado.", "무례한 행동."),
    ("puntual", "시간을 잘 지키는", "adj", "Siempre es muy puntual.", "그는 항상 시간을 엄수해요."),
    ("trabajador", "근면한 / 성실한", "adj", "Un equipo muy trabajador.", "매우 성실한 팀."),
    ("perezoso", "게으른", "adj", "Un domingo perezoso.", "게으름 피우는 일요일."),
    ("vago", "게으른", "adj", "No seas vago, levántate.", "게으름 피우지 말고 일어나."),
    ("tímido", "수줍음 많은 / 내성적인", "adj", "Un niño tímido pero dulce.", "수줍음 많지만 다정한 아이."),
    ("extrovertido", "외향적인", "adj", "Tiene un carácter extrovertido.", "그녀는 외향적인 성격이에요."),
    ("sensible", "민감한 / 감수성 풍부한", "adj", "Una persona muy sensible.", "매우 감수성이 풍부한 사람."),
    ("orgulloso", "자랑스러운 / 오만한", "adj", "Estoy orgulloso de ti.", "네가 정말 자랑스러워."),
    ("humilde", "겸손한", "adj", "Un sabio humilde.", "겸손한 현자."),
    ("curioso", "호기심 많은", "adj", "Una mente curiosa.", "호기심 가득한 마음."),
    ("silencioso", "조용한", "adj", "Una noche silenciosa.", "고요한 밤."),
    ("luminoso", "밝은 / 빛나는", "adj", "Un apartamento muy luminoso.", "채광이 아주 좋은 아파트."),
    ("brillante", "빛나는 / 총명한", "adj", "Una idea brillante.", "기발하고 빛나는 아이디어."),
    ("estrecho", "좁은", "adj", "Una calle muy estrecha.", "매우 좁은 골목길."),
    ("ancho", "넓은", "adj", "Una avenida ancha.", "넓은 대로."),
    ("profundo", "깊은", "adj", "Un río muy profundo.", "매우 깊은 강."),
    ("superficial", "얕은 / 피상적인", "adj", "Una herida superficial.", "얕은 찰과상."),
    ("antiguo", "고대의 / 오래된", "adj", "Un palacio antiguo.", "유서 깊은 고대 궁전."),
    ("moderno", "현대적인", "adj", "Arte moderno vanguardista.", "현대 아방가르드 예술."),
    ("típico", "전형적인 / 대표적인", "adj", "Un plato típico de España.", "스페인의 대표적 향토 요리."),
    ("original", "독창적인 / 원래의", "adj", "Una idea muy original.", "매우 독창적인 아이디어."),
    ("natural", "자연스러운 / 천연의", "adj", "Jugo natural sin conservantes.", "방부제 없는 천연 주스."),
    ("secreto", "비밀의", "adj", "Un pasaje secreto.", "비밀 통로."),
    ("público", "공공의 / 대중의", "adj", "Transporte público eficiente.", "효율적인 대중교통."),
    ("gratis", "무료의", "adj", "Entrada gratis para niños.", "어린이 무료입장."),
    ("hola", "안녕하세요", "adj", "¡Hola! ¿Cómo estás?", "안녕! 어떻게 지내니?"),
    ("buenos días", "좋은 아침입니다", "adj", "¡Buenos días a todos!", "모두 좋은 아침입니다!"),
    ("buenas tardes", "좋은 오후입니다", "adj", "Buenas tardes, señor.", "안녕하세요, 손님."),
    ("buenas noches", "좋은 밤 되세요 (안녕히 주무세요)", "adj", "Buenas noches, que descanses.", "좋은 밤 되세요, 푹 쉬세요."),
    ("gracias", "감사합니다", "adj", "Muchas gracias por todo.", "모든 것에 정말 감사드립니다."),
    ("de nada", "천만에요 (별말씀을요)", "adj", "De nada, es un placer.", "천만에요, 기쁨인걸요."),
    ("por favor", "부탁합니다 / 제발", "adj", "Un café solo, por favor.", "에스프레소 한 잔 부탁합니다."),
    ("perdón", "실례합니다 / 미안합니다", "adj", "Perdón, no fue mi intención.", "미안해요, 그럴 의도가 아니었어요."),
    ("disculpe", "실례합니다 (존칭)", "adj", "Disculpe, ¿dónde está la caja?", "실례지만 계산대가 어디인가요?"),
    ("lo siento", "죄송합니다", "adj", "Lo siento mucho por la demora.", "늦어서 정말 죄송합니다."),
    ("adiós", "안녕히 가세요 / 잘 가", "adj", "¡Adiós! Hasta la vista.", "안녕! 또 만나요."),
    ("hasta luego", "나중에 봐요", "adj", "Nos vemos, hasta luego.", "우리 또 봐요, 나중에 만나요."),
    ("hasta pronto", "곧 만나요", "adj", "Hasta pronto, amigo.", "곧 또 보자, 친구."),
    ("hasta mañana", "내일 만나요", "adj", "Hasta mañana en clase.", "내일 수업에서 만나요."),
    ("mucho gusto", "만나서 반가워요", "adj", "Mucho gusto en conocerte.", "만나 뵙게 되어 정말 반갑습니다."),
    ("encantado", "반갑습니다 (남성)", "adj", "Encantado de conocerle.", "만나서 반갑습니다."),
    ("encantada", "반갑습니다 (여성)", "adj", "Encantada de conocerte.", "만나서 반가워."),
    ("bienvenido", "환영합니다", "adj", "Bienvenido a España.", "스페인에 오신 것을 환영합니다."),
    ("buen provecho", "맛있게 드세요", "adj", "¡Buen provecho a todos!", "모두 맛있게 식사하세요!"),
    ("salud", "건배! / 건강하세요", "adj", "¡Salud y buena suerte!", "건배 그리고 행운을 빕니다!"),
    ("felicidades", "축하합니다", "adj", "¡Felicidades por tu boda!", "결혼 축하합니다!"),
    ("enhorabuena", "축하합니다 (칭찬)", "adj", "¡Enhorabuena por el premio!", "수상 축하드립니다!"),
    ("buena suerte", "행운을 빕니다", "adj", "¡Buena suerte en el examen!", "시험에 행운을 빌어요!"),
    ("cuídate", "몸조심해 / 잘 지내", "adj", "Cuídate mucho, amigo.", "몸조심하고 잘 지내, 친구."),
    ("vale", "알겠어 / 좋아 (스페인 빈출)", "adj", "Vale, de acuerdo.", "좋아, 그렇게 하자."),
    ("de acuerdo", "동의해 / 좋아", "adj", "Estoy de acuerdo contigo.", "네 말에 전적으로 동의해."),
    ("claro que sí", "물론이지요", "adj", "¡Claro que sí, con gusto!", "물론이죠, 기꺼이요!"),
    ("por supuesto", "당연하지", "adj", "Por supuesto que te ayudo.", "당연히 도와줘야지."),
    ("no pasa nada", "괜찮아 (별일 아니야)", "adj", "Tranquilo, no pasa nada.", "안심해, 아무 일도 아니야."),
    ("tengo hambre", "배고파요", "adj", "Tengo mucha hambre ahora.", "지금 너무 배고파요."),
    ("tengo sed", "목말라요", "adj", "Tengo sed, quiero agua.", "목말라요, 물 마시고 싶어요."),
    ("tengo frío", "추워요", "adj", "Cierra la ventana, tengo frío.", "창문 닫아줘, 추워."),
    ("tengo calor", "더워요", "adj", "Enciende el aire, tengo calor.", "에어컨 켜줘, 더워."),
    ("tengo sueño", "졸려요", "adj", "Me voy a dormir, tengo sueño.", "잘래, 졸려."),
    ("tengo prisa", "급해요 / 서둘러야 해요", "adj", "Tengo prisa, el tren se va.", "급해요, 기차가 떠나요."),
    ("tengo miedo", "무서워요", "adj", "No tengas miedo, estoy aquí.", "무서워하지 마, 내가 여기 있잖아."),
    ("qué tal", "어때? / 어떻게 지내?", "adj", "¡Hola! ¿Qué tal todo?", "안녕! 모든 게 다 잘 돼가?"),
    ("cómo te va", "어떻게 지내니?", "adj", "¿Cómo te va en la escuela?", "학교생활은 어떻게 지내니?"),
    ("cuánto tiempo", "오랜만이야", "adj", "¡Cuánto tiempo sin verte!", "정말 오랜만이다!"),
    ("nos vemos", "또 봐요", "adj", "Nos vemos el fin de semana.", "주말에 또 봐요."),
    ("hasta la vista", "다시 만날 때까지 안녕", "adj", "¡Hasta la vista, amigos!", "다시 만날 때까지 안녕, 친구들!"),
]

# Combine and deduplicate
all_data = VERBS + NOUNS + PREPS_AND_CONJS + ADJECTIVES_AND_PHRASES
seen = set()
unique_words = []

for item in all_data:
    key = item[0].lower().strip()
    if key not in seen:
        seen.add(key)
        unique_words.append(list(item))

print(f"Total Unique Vocabulary Words: {len(unique_words)}")

# Prepare Compact JS representation
# Store as: const RAW_WORDS = [...]; const SPANISH_WORDS = RAW_WORDS.map((w, idx) => ({ id: idx + 1, es: w[0], ko: w[1], cat: w[2], ex_es: w[3], ex_ko: w[4] }));
json_str = json.dumps(unique_words, ensure_ascii=False)

js_replacement = f"""    /* ========================================================
       스페인어 핵심 단어 데이터베이스 (총 {len(unique_words)}개 고빈도 일상 단어 탑재)
       카테고리: verb (동사), noun (명사), prep (전치사/접속사/부사), adj (형용사/표현)
       ======================================================== */
    const RAW_WORDS = {json_str};
    const SPANISH_WORDS = RAW_WORDS.map((w, idx) => ({{
      id: idx + 1,
      es: w[0],
      ko: w[1],
      cat: w[2],
      ex_es: w[3],
      ex_ko: w[4]
    }}));"""

# Read index.html
html_path = "C:/Users/jckim/Desktop/project1_260904/index.html"
with open(html_path, "r", encoding="utf-8") as f:
    content = f.read()

# Replace the SPANISH_WORDS array in index.html
pattern = r"/\* ========================================================\s*스페인어 핵심 단어 데이터베이스[\s\S]*?const SPANISH_WORDS\s*=\s*\[[\s\S]*?\];"
if re.search(pattern, content):
    new_content = re.sub(pattern, js_replacement, content, count=1)
    print("Found and replaced SPANISH_WORDS in index.html!")
else:
    # Alternative check if RAW_WORDS already exists
    pattern2 = r"/\* ========================================================\s*스페인어 핵심 단어 데이터베이스[\s\S]*?const SPANISH_WORDS\s*=\s*RAW_WORDS\.map[\s\S]*?\)\);"
    if re.search(pattern2, content):
        new_content = re.sub(pattern2, js_replacement, content, count=1)
        print("Found and updated existing RAW_WORDS in index.html!")
    else:
        print("ERROR: Pattern not matched!")
        new_content = content

# Update Hero section counter: "80+ 개" -> "1,000+ 개"
new_content = new_content.replace("80+ 개", f"{len(unique_words):,}+ 개")
new_content = new_content.replace("총 80개 단어", f"총 {len(unique_words):,}개 단어")
new_content = new_content.replace("80개 이상의", f"{len(unique_words):,}개 이상의")

with open(html_path, "w", encoding="utf-8") as f:
    f.write(new_content)

print(f"Successfully updated index.html with {len(unique_words)} words!")
